"""Shared timeout budgets for managed Codex session turns."""

from __future__ import annotations

SEND_TURN_ACTIVITY_START_TO_CLOSE_SECONDS = 3600
SEND_TURN_ACTIVITY_SCHEDULE_TO_CLOSE_SECONDS = 3900
SEND_TURN_ACTIVITY_HEARTBEAT_TIMEOUT_SECONDS = 30
SEND_TURN_ACTIVITY_SAFETY_BUFFER_SECONDS = 60

DEFAULT_CODEX_TURN_COMPLETION_TIMEOUT_SECONDS = (
    SEND_TURN_ACTIVITY_START_TO_CLOSE_SECONDS
    - SEND_TURN_ACTIVITY_SAFETY_BUFFER_SECONDS
)
MAX_CODEX_TURN_COMPLETION_TIMEOUT_SECONDS = (
    SEND_TURN_ACTIVITY_START_TO_CLOSE_SECONDS
    - SEND_TURN_ACTIVITY_SAFETY_BUFFER_SECONDS
)
