version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./model_data:/root/.ollama/models
      - ./scripts/entrypoint-ollama.sh:/entrypoint-ollama.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint-ollama.sh"]
    networks:
      - local-network
    env_file:
      - .env
    environment:
      - OLLAMA_CONTEXT_LENGTH=32768
      - OLLAMA_FLASH_ATTENTION=true
      - OLLAMA_KV_CACHE_TYPE=q4_0

networks:
  local-network:
    external: true
