services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.39
    container_name: openhands-app
    pull_policy: always
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.openhands-state-data:/.openhands-state # For persistent state
      - ./config.toml:/app/openhands/config.toml:ro # Mount project-specific config
      # To allow OpenHands to work on the current project's code,
      # you might need to uncomment and adjust the following line:
      - .:/workspace # Mount current directory to /workspace in container
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.39-nikolaik
      - LOG_ALL_EVENTS=true
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - local-network
    env_file:
      - .env

networks:
  local-network:
    external: true
