version: '3.8'

services:
  downloader:
    build:
      context: .
      dockerfile: ./rag/Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./models:/app/models
      - ./moonai:/app/moonai
      - ./scripts:/app/scripts
    working_dir: /app
    entrypoint: ["bash", "-c", "/app/scripts/get-qwen.sh"]
    networks:
      - local-network

networks:
  local-network:
    external: true
