version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./models:/root/.ollama/models
      - ./scripts/entrypoint-ollama.sh:/entrypoint-ollama.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint-ollama.sh"]
    networks:
      - local-network
    env_file:
      - .env

networks:
  local-network:
    external: true
