version: '3.8'

services:
  ui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 8080:8080
    environment:
      - OPENAI_API_BASE_URL=http://api:8000/v1
      - WEBUI_AUTH=false
      - ENABLE_OLLAMA_API=false
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - local-network

  api:
    build:
      context: .
      dockerfile: ./api_service/Dockerfile
    image: ghcr.io/moonladderstudios/moonmind:latest # This might need to be rebuilt
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
      - FASTAPI_RELOAD=${FASTAPI_RELOAD:-0}
      - MODEL_CONTEXT_PROTOCOL_ENABLED=true
      - MODEL_CONTEXT_PROTOCOL_PORT=8000
      - MODEL_CONTEXT_PROTOCOL_HOST=0.0.0.0
      # Add PYTHONPATH if pip install -e . isn't sufficient due to WORKDIR context
      # - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./model_data:/app/model_data
      # Mount the entire api_service directory
      - ./api_service:/app/api_service:ro
      - ./moonmind:/app/moonmind:ro
      # pyproject.toml is already copied in Dockerfile, but mount if local changes needed for deps
      # - ./pyproject.toml:/app/pyproject.toml:ro
    command: >
      sh -c "
      if [ \"$FASTAPI_RELOAD\" = \"True\" ]; then
        uvicorn api_service.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/api_service --reload-dir /app/moonmind;
      else
        uvicorn api_service.main:app --host 0.0.0.0 --port 8000;
      fi"
    networks:
      - local-network
    labels:
      - "ai.model.context.protocol.version=0.1"
      - "ai.model.context.protocol.endpoint=/context"

  init-vector-db:
    build:
      context: .
      dockerfile: ./api_service/Dockerfile
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
      - QDRANT_URL=http://${QDRANT_HOST}:${QDRANT_PORT}
    env_file:
      - .env
    volumes:
      - ./moonmind:/app/moonmind:ro
      - ./scripts:/app/scripts:ro
      - ./model_data:/app/model_data:ro
    command: >
      sh -c "
      if [ "$INIT_DATABASE" = "true" ]; then
        echo 'Attempting to initialize vector database...'
        export PYTHONPATH=/app && python /app/scripts/init_vector_db.py;
      else
        echo 'INIT_DATABASE not set to true, skipping vector DB initialization.';
      fi"
    networks:
      - local-network
    restart: "no"
    depends_on:
      api:
        condition: service_started

volumes:
  open-webui:

networks:
  local-network:
    external: true
