version: '3.8'

services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.39
    container_name: openhands-app
    pull_policy: always
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.openhands-state-data:/.openhands-state # For persistent state
      - ./config.toml:/.openhands-state/config.toml:ro # Mount project-specific config
      # To allow OpenHands to work on the current project's code,
      # you might need to uncomment and adjust the following line:
      - .:/workspace # Mount current directory to /workspace in container
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.39-nikolaik
      - LOG_ALL_EVENTS=true
      # If you mount the workspace (e.g., to /workspace as above),
      # you may need to set the workspace path for OpenHands.
      # This can be done via an environment variable overriding config.toml, e.g.:
      - OPENHANDS__CORE__WORKSPACE_BASE=/workspace # Adjusted from WORKSPACE_MOUNT_PATH to WORKSPACE_BASE
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - local-network
    env_file:
      - .env

networks:
  local-network:
    external: true
