version: '3.8'

services:
  downloader:
    build:
      context: .
      dockerfile: ./api_service/Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./model_data:/app/model_data
      - ./moonmind:/app/moonmind
      - ./scripts:/app/scripts
    working_dir: /app
    entrypoint: ["bash", "-c", "/app/scripts/get-qwen.sh"]
    networks:
      - local-network

networks:
  local-network:
    external: true
