version: '3.8'

services:
  pytest:
    build:
      context: .
      dockerfile: ./rag/Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./moonai:/app/moonai
      - ./tests:/app/tests
    working_dir: /app
    command: ["bash", "-c", "pip install pytest && pytest -s /app/tests/${TEST_TYPE}"]
    networks:
      - local-network

networks:
  local-network:
    external: true
