"""Omnigent control-plane durable aggregates and repositories.

Source: MoonLadderStudios/MoonMind#3703 ([Omnigent control plane 2/11]).

Separates the overloaded ``OmnigentBridgeSession`` lifecycle model into explicit
durable aggregates -- canonical sessions, turn attempts, observations, commands,
and reconciliation decisions -- behind narrow repository interfaces that hide
SQLAlchemy from domain and application code.
"""

from __future__ import annotations

from .backfill import (
    BackfillPlan,
    BackfillReport,
    plan_backfill,
    run_backfill,
)
from .records import (
    ALIAS_STATE_ACTIVE,
    ALIAS_STATE_DIAGNOSTIC,
    ALIAS_STATE_QUARANTINED,
    CURRENT_SCHEMA_VERSION,
    SUPPORTED_SCHEMA_VERSIONS,
    TURN_STATES,
    TURN_STATE_ACCEPTED,
    TURN_STATE_DELIVERY_UNKNOWN,
    TURN_STATE_DISPATCHING,
    TURN_STATE_PREPARED,
    TURN_STATE_RUNNING,
    TURN_STATE_TERMINAL,
    AmbiguousAuthorityError,
    ChatBindingAliasRecord,
    CommandIdempotencyConflictError,
    CommandRecord,
    ConflictingSessionAuthorityError,
    DecisionRecord,
    ObservationRecord,
    OmnigentControlPlaneError,
    SessionRecord,
    TerminalSessionOverwriteError,
    TurnAttemptRecord,
    TurnIdempotencyConflictError,
    UnknownSchemaVersionError,
    compute_digest,
)
from .repositories import (
    ChatBindingAliasRepository,
    CommandRepository,
    ControlPlaneRepositories,
    DecisionRepository,
    ObservationRepository,
    OmnigentControlPlaneStore,
    SessionRepository,
    TurnAttemptRepository,
)
from .turn_contract import (
    CANONICAL_TERMINAL_SESSION_STATES,
    CLEANUP_COMPLETE,
    CLEANUP_FENCED,
    CLEANUP_IN_PROGRESS,
    CLEANUP_PENDING,
    CLEANUP_RELEASED,
    LIFECYCLE_OWNERSHIP_MATRIX,
    OUTBOUND_SCAN_SOURCE_KINDS,
    SESSION_ALLOCATING_SOURCE_KINDS,
    TERMINAL_CLEANUP_STATES,
    BranchRequiredError,
    CallerAuthorityError,
    ChatCapability,
    ChatCapabilityDecision,
    CleanupDecision,
    CleanupDisposition,
    CleanupFenceError,
    CleanupOperation,
    ImmutableSessionDimensions,
    Lifecycle,
    LifecycleActivity,
    LifecycleOwnership,
    RecoveryDecision,
    RecoveryEvidence,
    RecoveryMode,
    RemediationAuthorityError,
    RemediationTurnIntent,
    SessionTerminalError,
    TurnCommandStep,
    TurnContractError,
    TurnSourceKind,
    TurnSubmissionPlan,
    TurnSubmissionRequest,
    admit_continuation,
    decide_recovery,
    derive_chat_capability,
    evaluate_cleanup_admission,
    idempotency_scope_for,
    plan_turn_submission,
    validate_remediation_authority,
)
from .turn_service import (
    SUBMIT_TURN_COMMAND_TYPE,
    OmnigentTurnService,
    TurnSubmissionOutcome,
)

__all__ = [
    "ALIAS_STATE_ACTIVE",
    "ALIAS_STATE_DIAGNOSTIC",
    "ALIAS_STATE_QUARANTINED",
    "CURRENT_SCHEMA_VERSION",
    "SUPPORTED_SCHEMA_VERSIONS",
    "TURN_STATES",
    "TURN_STATE_ACCEPTED",
    "TURN_STATE_DELIVERY_UNKNOWN",
    "TURN_STATE_DISPATCHING",
    "TURN_STATE_PREPARED",
    "TURN_STATE_RUNNING",
    "TURN_STATE_TERMINAL",
    "AmbiguousAuthorityError",
    "BackfillPlan",
    "BackfillReport",
    "ChatBindingAliasRecord",
    "ChatBindingAliasRepository",
    "CommandIdempotencyConflictError",
    "CommandRecord",
    "CommandRepository",
    "ConflictingSessionAuthorityError",
    "ControlPlaneRepositories",
    "DecisionRecord",
    "DecisionRepository",
    "ObservationRecord",
    "ObservationRepository",
    "OmnigentControlPlaneError",
    "OmnigentControlPlaneStore",
    "SessionRecord",
    "SessionRepository",
    "TerminalSessionOverwriteError",
    "TurnAttemptRecord",
    "TurnAttemptRepository",
    "TurnIdempotencyConflictError",
    "UnknownSchemaVersionError",
    "compute_digest",
    "plan_backfill",
    "run_backfill",
    # --- #3707 canonical session/turn ownership contract ---
    "CANONICAL_TERMINAL_SESSION_STATES",
    "CLEANUP_COMPLETE",
    "CLEANUP_FENCED",
    "CLEANUP_IN_PROGRESS",
    "CLEANUP_PENDING",
    "CLEANUP_RELEASED",
    "LIFECYCLE_OWNERSHIP_MATRIX",
    "OUTBOUND_SCAN_SOURCE_KINDS",
    "SESSION_ALLOCATING_SOURCE_KINDS",
    "TERMINAL_CLEANUP_STATES",
    "BranchRequiredError",
    "CallerAuthorityError",
    "ChatCapability",
    "ChatCapabilityDecision",
    "CleanupDecision",
    "CleanupDisposition",
    "CleanupFenceError",
    "CleanupOperation",
    "ImmutableSessionDimensions",
    "Lifecycle",
    "LifecycleActivity",
    "LifecycleOwnership",
    "RecoveryDecision",
    "RecoveryEvidence",
    "RecoveryMode",
    "RemediationAuthorityError",
    "RemediationTurnIntent",
    "SessionTerminalError",
    "TurnCommandStep",
    "TurnContractError",
    "TurnSourceKind",
    "TurnSubmissionPlan",
    "TurnSubmissionRequest",
    "admit_continuation",
    "decide_recovery",
    "derive_chat_capability",
    "evaluate_cleanup_admission",
    "idempotency_scope_for",
    "plan_turn_submission",
    "validate_remediation_authority",
    # --- #3707 durable turn-submission executor ---
    "SUBMIT_TURN_COMMAND_TYPE",
    "OmnigentTurnService",
    "TurnSubmissionOutcome",
]
