"""Omnigent control-plane durable aggregates and repositories.

Source: MoonLadderStudios/MoonMind#3703 ([Omnigent control plane 2/11]).

Separates the overloaded ``OmnigentBridgeSession`` lifecycle model into explicit
durable aggregates -- canonical sessions, turn attempts, observations, commands,
and reconciliation decisions -- behind narrow repository interfaces that hide
SQLAlchemy from domain and application code.
"""

from __future__ import annotations

from . import metrics, spans, telemetry
from .backfill import (
    BackfillPlan,
    BackfillReport,
    plan_backfill,
    run_backfill,
)
from .readiness import (
    AdmissionReadiness,
    CapabilityReadiness,
    ReadinessCapability,
    ReadinessInputs,
    ReadinessState,
    evaluate_admission_readiness,
)
from .spans import (
    OMNIGENT_SPANS,
    SAFE_SPAN_ATTRIBUTES,
    omnigent_span,
    sanitize_span_attributes,
)
from .stuck_state import (
    AutomatedResponse,
    ResponseAction,
    SessionSignals,
    StuckStateFinding,
    StuckStatePolicy,
    StuckStateReason,
    detect_stuck_state,
    plan_response,
)
from .stuck_state_reconciliation import (
    DiagnosticPublisher,
    ReconcileDispatcher,
    StuckStateInspection,
    StuckStateReconciliationService,
    StuckStateSweepResult,
    inspect_stuck_state,
)
from .timeline import (
    SessionTimeline,
    TimelineStatus,
    build_timeline,
)
from .records import (
    ALIAS_STATE_ACTIVE,
    ALIAS_STATE_DIAGNOSTIC,
    ALIAS_STATE_QUARANTINED,
    APPLIED_OUTCOMES,
    CLEANUP_STATE_CLAIMED,
    CLEANUP_STATE_COMPLETE,
    CLEANUP_STATE_UNCLAIMED,
    CLEANUP_STATES,
    COMMAND_STATE_APPLIED,
    COMMAND_STATE_CLAIMED,
    COMMAND_STATE_DELIVERY_UNKNOWN,
    COMMAND_STATE_FAILED,
    COMMAND_STATE_PENDING,
    COMMAND_STATES,
    COMMAND_TERMINAL_STATES,
    CONFLICT_OUTCOMES,
    CURRENT_SCHEMA_VERSION,
    SUPPORTED_SCHEMA_VERSIONS,
    TURN_STATES,
    TURN_STATE_ACCEPTED,
    TURN_STATE_DELIVERY_UNKNOWN,
    TURN_STATE_DISPATCHING,
    TURN_STATE_PREPARED,
    TURN_STATE_RUNNING,
    TURN_STATE_TERMINAL,
    AmbiguousAuthorityError,
    CasResult,
    ChatBindingAliasRecord,
    CleanupAuthorityRecord,
    CommandIdempotencyConflictError,
    CommandRecord,
    ConflictingSessionAuthorityError,
    ControlPlaneConflictError,
    ControlPlaneOutcome,
    DecisionRecord,
    FencingConflictError,
    FencingScope,
    NotCommandOwnerError,
    ObservationRecord,
    OmnigentControlPlaneError,
    RevisionConflictError,
    SessionRecord,
    TerminalSessionOverwriteError,
    TurnAttemptRecord,
    TurnIdempotencyConflictError,
    UnknownSchemaVersionError,
    compute_digest,
)
from .repositories import (
    ChatBindingAliasRepository,
    CleanupAuthorityRepository,
    CommandRepository,
    ControlPlaneRepositories,
    DecisionRepository,
    ObservationRepository,
    OmnigentControlPlaneStore,
    SessionRepository,
    TurnAttemptRepository,
)
from .turn_commands import (
    CanonicalSessionBootstrap,
    CanonicalTurnAuthorityUnavailable,
    CanonicalTurnCommandClaim,
    CanonicalTurnCommandService,
)
from .turn_sources import (
    TURN_SOURCE_KINDS,
    TURN_SOURCE_SCHEMA,
    TURN_SOURCE_VERSION,
    is_valid_turn_source,
    normalize_turn_source,
    turn_source_for_command_type,
    validate_turn_source,
)

__all__ = [
    "ALIAS_STATE_ACTIVE",
    "ALIAS_STATE_DIAGNOSTIC",
    "ALIAS_STATE_QUARANTINED",
    "APPLIED_OUTCOMES",
    "CLEANUP_STATE_CLAIMED",
    "CLEANUP_STATE_COMPLETE",
    "CLEANUP_STATE_UNCLAIMED",
    "CLEANUP_STATES",
    "COMMAND_STATE_APPLIED",
    "COMMAND_STATE_CLAIMED",
    "COMMAND_STATE_DELIVERY_UNKNOWN",
    "COMMAND_STATE_FAILED",
    "COMMAND_STATE_PENDING",
    "COMMAND_STATES",
    "COMMAND_TERMINAL_STATES",
    "CanonicalTurnAuthorityUnavailable",
    "CanonicalSessionBootstrap",
    "CanonicalTurnCommandClaim",
    "CanonicalTurnCommandService",
    "TURN_SOURCE_KINDS",
    "TURN_SOURCE_SCHEMA",
    "TURN_SOURCE_VERSION",
    "is_valid_turn_source",
    "normalize_turn_source",
    "turn_source_for_command_type",
    "validate_turn_source",
    "CONFLICT_OUTCOMES",
    "CURRENT_SCHEMA_VERSION",
    "SUPPORTED_SCHEMA_VERSIONS",
    "TURN_STATES",
    "TURN_STATE_ACCEPTED",
    "TURN_STATE_DELIVERY_UNKNOWN",
    "TURN_STATE_DISPATCHING",
    "TURN_STATE_PREPARED",
    "TURN_STATE_RUNNING",
    "TURN_STATE_TERMINAL",
    "AmbiguousAuthorityError",
    "BackfillPlan",
    "BackfillReport",
    "CasResult",
    "ChatBindingAliasRecord",
    "ChatBindingAliasRepository",
    "CleanupAuthorityRecord",
    "CleanupAuthorityRepository",
    "CommandIdempotencyConflictError",
    "CommandRecord",
    "CommandRepository",
    "ConflictingSessionAuthorityError",
    "ControlPlaneConflictError",
    "ControlPlaneOutcome",
    "ControlPlaneRepositories",
    "DecisionRecord",
    "DecisionRepository",
    "FencingConflictError",
    "FencingScope",
    "NotCommandOwnerError",
    "ObservationRecord",
    "ObservationRepository",
    "OmnigentControlPlaneError",
    "OmnigentControlPlaneStore",
    "RevisionConflictError",
    "SessionRecord",
    "SessionRepository",
    "TerminalSessionOverwriteError",
    "TurnAttemptRecord",
    "TurnAttemptRepository",
    "TurnIdempotencyConflictError",
    "UnknownSchemaVersionError",
    "compute_digest",
    "plan_backfill",
    "run_backfill",
    "telemetry",
    "metrics",
    "spans",
    # semantic spans
    "OMNIGENT_SPANS",
    "SAFE_SPAN_ATTRIBUTES",
    "omnigent_span",
    "sanitize_span_attributes",
    # operator timeline
    "SessionTimeline",
    "TimelineStatus",
    "build_timeline",
    # stuck-state detector + automated response
    "AutomatedResponse",
    "ResponseAction",
    "SessionSignals",
    "StuckStateFinding",
    "StuckStatePolicy",
    "StuckStateReason",
    "detect_stuck_state",
    "plan_response",
    "DiagnosticPublisher",
    "ReconcileDispatcher",
    "StuckStateInspection",
    "StuckStateReconciliationService",
    "StuckStateSweepResult",
    "inspect_stuck_state",
    # new-admission readiness
    "AdmissionReadiness",
    "CapabilityReadiness",
    "ReadinessCapability",
    "ReadinessInputs",
    "ReadinessState",
    "evaluate_admission_readiness",
]
