apiVersion: moonmind/v1
kind: Readers
metadata:
  name: moonmind-example
  description: Example collection of data readers for MoonMind
spec:
  readers:
    - type: GithubRepositoryReader
      enabled: true
      init:
        github_client:
          _type: llama_index.readers.github.github_client.GithubClient
          _init:
            github_token:
              secretRef:
                provider: profile
                key: GITHUB_TOKEN
            verbose: true
            concurrent_requests: 10
            timeout: 5
            retries: 3
        owner: MoonLadderStudios
        repo: MoonMind
        use_parser: true
        verbose: true
        concurrent_requests: 10
        timeout: 5
        retries: 3
        filter_directories:
          - ["tests"]
          - "EXCLUDE"
        filter_file_extensions:
          - [".md", ".py", ".yaml"]
          - "INCLUDE"
      load_data:
        - branch: main

    - type: ConfluenceReader
      enabled: true
      settings:
        base_url: https://moonladder.atlassian.net/wiki
        cloud: true                       # true = Confluence Cloud

        # --- option A: single API token --------------------------------
        api_token:
          secretRef:
            provider: env
            key: ATLASSIAN_API_KEY
        # api_token: atsu_xxxxx...            # literal fallback

        # --- option B: basic-auth (username + password) --------------
        # user_name:
        #   secretRef: {provider: env, key: ATLASSIAN_USERNAME}
        # password:
        #   secretRef: {provider: vault, key: secret/confluence#password}

        # --- option C: OAuth 2.0 dict ---------------------------------
        # oauth2:
        #   secretRef: {provider: file, key: /secrets/confluence_oauth.json}

        # --- option D: Cookie jar -------------------------------------
        # cookies:
        #   secretRef: {provider: file, key: /secrets/confluence_cookies.json}

        include_attachments: false

      sources:
        - space_key: MOON
          page_ids: ["123456", "789012"]
          page_status: current
          max_num_results: 50
        - space_key: DOCS
          include_attachments: true

    - type: GoogleDriveReader
      enabled: true
      settings:
        # --- option A: service-account key ---------------------------
        service_account_key:
          secretRef:
            provider: file
            key: /secrets/gdrive_service_account.json

        # --- option B: cached OAuth “authorized_user_info” -----------
        # authorized_user_info:
        #   secretRef:
        #     provider: profile
        #     key: gdrive_user_creds

        # --- option C: full client_config (interactive flow) ---------
        # client_config:
        #   secretRef:
        #     provider: env
        #     key: GDRIVE_CLIENT_CONFIG_JSON

        is_cloud: true                 # don’t write token.json to disk
        drive_id: 0Bxxxxxxxxxxxxxxxxxxxxxxxxx  # optional—for shared drives

      sources:
        - folder_id: MoonMindDocs
          recursive: true
          mime_types: ["application/vnd.google-apps.document"]
        - file_ids: [file_id_1, file_id_2]
