"""Save before owned cleanup, then finish from saved bytes (MoonMind#4016).

The generic realizer's own cleanup and finalization owners drive the real
workspace publication service and production artifact gateway (sqlite plus a
local blob volume). After the owned workspace is removed, finalization
restores the exact saved candidate from its checkpoint without a provider
driver, a host, or any repository credential, and resumes only the phase that
had not finished.
"""

from __future__ import annotations

import asyncio
import hashlib
import shutil
import subprocess
from pathlib import Path
from types import SimpleNamespace

import pytest
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from api_service.db.models import Base
from moonmind.omnigent.bridge_artifacts import TemporalOmnigentArtifactGateway
from moonmind.omnigent.realizers.generic_host import GenericOmnigentHostRealizer
from moonmind.omnigent.runtime_bindings import (
    InMemoryStableRuntimeBindingStore,
    RuntimeBindingSessionAuthoritySink,
    RuntimeBindingState,
)
from moonmind.omnigent.workspace_publication import OmnigentWorkspacePublicationService
from moonmind.schemas.agent_runtime_models import (
    AgentExecutionRequest,
    AgentRunResult,
    OmnigentExecutionPlanBinding,
)
from moonmind.workflows.temporal.artifacts import (
    LocalTemporalArtifactStore,
    TemporalArtifactService,
)
from moonmind.workflows.temporal.runtime.workspace_locators import (
    SandboxWorkspaceRecord,
    SandboxWorkspaceRecordStore,
)

WORKFLOW_ID = "saved-finalization"
STEP_ID = f"{WORKFLOW_ID}:run-1:implement:execution:1"
WORKSPACE_ID = hashlib.sha256(f"{WORKFLOW_ID}:{STEP_ID}".encode()).hexdigest()[:24]


def _git(workspace: Path, *args: str) -> str:
    return subprocess.check_output(
        ["git", "-C", str(workspace), *args], text=True
    ).strip()


def _candidate_workspace(root: Path) -> tuple[Path, str]:
    workspace = root / "temporal_sandbox" / WORKSPACE_ID / "repo"
    workspace.mkdir(parents=True)
    _git(workspace, "init", "-q")
    _git(workspace, "config", "user.name", "Journey")
    _git(workspace, "config", "user.email", "journey@example.invalid")
    (workspace / "app.py").write_text("print('base')\n")
    _git(workspace, "add", ".")
    _git(workspace, "commit", "-qm", "base")
    # Generated work that never reached any remote.
    (workspace / "generated.py").write_text("print('generated by the run')\n")
    _git(workspace, "add", ".")
    _git(workspace, "commit", "-qm", "agent candidate")
    (workspace / "app.py").write_text("print('uncommitted edit')\n")
    SandboxWorkspaceRecordStore(root).ensure(
        SandboxWorkspaceRecord(WORKSPACE_ID, WORKFLOW_ID, STEP_ID, "repo")
    )
    return workspace, _git(workspace, "rev-parse", "HEAD")


async def _request(gateway: TemporalOmnigentArtifactGateway) -> AgentExecutionRequest:
    request = AgentExecutionRequest.model_validate(
        {
            "agentKind": "external",
            "agentId": "omnigent",
            "correlationId": WORKFLOW_ID,
            "idempotencyKey": "saved-finalization-attempt",
            "workspaceSpec": {
                "repository": "MoonLadderStudios/MoonMind",
                "workspaceLocator": {
                    "kind": "sandbox",
                    "workspaceId": WORKSPACE_ID,
                    "relativePath": "repo",
                },
            },
            "stepExecution": {
                "workflowId": WORKFLOW_ID,
                "runId": "run-1",
                "logicalStepId": "implement",
                "executionOrdinal": 1,
                "stepExecutionId": STEP_ID,
                "runtimeContextPolicy": "fresh_agent_run",
            },
        }
    )
    task_input = b'{"objective":"keep the generated candidate"}'
    plan = b'{"steps":["implement"]}'
    input_ref = await gateway.write_bytes(
        request=request,
        name="input",
        payload=task_input,
        content_type="application/json",
        link_type="input",
    )
    plan_ref = await gateway.write_bytes(
        request=request,
        name="plan",
        payload=plan,
        content_type="application/json",
        link_type="input",
    )
    digest = hashlib.sha256(plan).hexdigest()
    return request.model_copy(
        update={
            "step_execution": request.step_execution.model_copy(
                update={
                    "omnigent_execution_plan": OmnigentExecutionPlanBinding(
                        planRef="omnigent-execution-plan:sha256:" + digest,
                        planDigest="sha256:" + digest,
                        planArtifactRef=plan_ref,
                        taskInputSnapshotRef=input_ref,
                        taskInputSnapshotDigest="sha256:"
                        + hashlib.sha256(task_input).hexdigest(),
                    )
                }
            )
        }
    )


class _NoCredentials:
    async def cleanup_all(self, handles):
        return []

    def __getattr__(self, name):
        raise AttributeError(
            f"finalization must not use repository credentials: {name}"
        )


def _owned_cleanup_realizer(
    store, publisher
) -> tuple[GenericOmnigentHostRealizer, list]:
    realizer = object.__new__(GenericOmnigentHostRealizer)
    released: list = []
    realizer._runtime_bindings = store
    realizer._turn_commands = None
    realizer._cleanup_authority = None
    realizer._artifacts = None
    realizer._workspace_publisher = publisher
    realizer._session_cleanup = SimpleNamespace(drain=None)
    realizer._host_runtime = SimpleNamespace(
        cleanup_authorities=lambda refs: _done(), cleanup_prepared=None
    )
    realizer._credentials = _NoCredentials()

    async def release_all(acquired):
        released.append(tuple(acquired))

    realizer._provider_leases = SimpleNamespace(release_all=release_all)
    realizer._host_leases = SimpleNamespace()

    async def no_provider(*_args, **_kwargs):
        raise AssertionError("finalization must not start another agent run")

    realizer._session_driver = no_provider
    return realizer, released


async def _done():
    return None


@pytest.mark.asyncio
async def test_saved_candidate_survives_owned_cleanup_and_finishes_without_rerun(
    tmp_path, monkeypatch
):
    root = tmp_path / "worker"
    workspace, head = _candidate_workspace(root)
    blob_root = tmp_path / "durable-artifacts"
    monkeypatch.setattr(
        TemporalArtifactService,
        "_build_store_from_settings",
        staticmethod(lambda: LocalTemporalArtifactStore(blob_root)),
    )
    engine = create_async_engine("sqlite+aiosqlite://", poolclass=StaticPool)
    async with engine.begin() as connection:
        await connection.run_sync(Base.metadata.create_all)
    sessions = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    try:
        gateway = TemporalOmnigentArtifactGateway(session_factory=sessions)
        request = await _request(gateway)
        store = InMemoryStableRuntimeBindingStore()
        binding = await store.create_initial(
            execution_plan_ref=request.step_execution.omnigent_execution_plan.plan_ref,
            idempotency_key=request.idempotency_key,
            provider_leases={},
        )
        sink = RuntimeBindingSessionAuthoritySink(store, binding)
        await sink.record_phase(
            "workspace",
            request.model_dump(
                by_alias=True,
                mode="json",
                exclude_none=True,
                include={
                    "agent_kind",
                    "agent_id",
                    "correlation_id",
                    "idempotency_key",
                    "step_execution",
                },
            )
            | {"workspaceSpec": dict(request.workspace_spec)},
        )
        # Confirmed compute is durable before any later finalization error.
        await sink.record_phase(
            "compute",
            AgentRunResult(summary="candidate generated").model_dump(
                by_alias=True, mode="json", exclude_none=True
            ),
        )
        publisher = OmnigentWorkspacePublicationService(root, artifact_gateway=gateway)
        realizer, released = _owned_cleanup_realizer(store, publisher)

        cleaned, _host = await realizer._cleanup(
            request=request,
            binding=sink.binding,
            host_lease=None,
            host_context=None,
            prepared=None,
            credential_handles=(),
            acquired=("provider-lease",),
        )

        assert cleaned.state is RuntimeBindingState.cleaned
        assert released == [("provider-lease",)]
        saved = cleaned.phaseResults["saved"]
        assert "publication" not in cleaned.phaseResults
        # Committed, usable references: the bytes read back match the digest.
        archive = await gateway.read_bytes(saved["archiveRef"])
        assert "sha256:" + hashlib.sha256(archive).hexdigest() == saved["archiveDigest"]
        assert saved["checkpointRef"].startswith("artifact://art_")

        # The owned host and its workspace volume are gone.
        shutil.rmtree(root)
        published: list[AgentRunResult] = []

        async def publish(bound, result):
            restored = publisher.resolve_request_workspace(bound)
            assert _git(restored, "rev-parse", "HEAD") == head
            assert (restored / "generated.py").read_text() == (
                "print('generated by the run')\n"
            )
            assert (restored / "app.py").read_text() == "print('uncommitted edit')\n"
            published.append(result)
            return result.model_copy(update={"summary": "published saved candidate"})

        realizer._publish_repository = publish
        # A fresh replacement worker: new gateway and service, same durable state.
        replacement = OmnigentWorkspacePublicationService(
            root,
            artifact_gateway=TemporalOmnigentArtifactGateway(session_factory=sessions),
        )
        realizer._workspace_publisher = replacement
        realizer._interrupted_admission_result = lambda *_args: _done()

        # Two concurrent deliveries share one owner: one restore, one publish.
        first, second = await asyncio.gather(
            realizer._reconcile_finalization(
                request, await store.get(binding.bindingId)
            ),
            realizer._reconcile_finalization(
                request, await store.get(binding.bindingId)
            ),
        )

        assert first == second
        assert first.summary == "published saved candidate"
        assert first.metadata["savedWorkspaceCheckpoint"] == saved
        assert first.metadata["workPreserved"] is True
        assert len(published) == 1
        phases = (await store.get(binding.bindingId)).phaseResults
        assert phases["saved"] == saved
        assert phases["restoration"]["restorationEvidenceRef"]
    finally:
        await engine.dispose()


@pytest.mark.asyncio
async def test_host_lost_successor_restores_confirmed_saved_bytes(
    tmp_path, monkeypatch
):
    """An interrupted attempt's saved bytes reach a distinct successor (#4627).

    The turn never produced compute. The realizer's own cleanup confirms the
    predecessor stopped and saves its surviving workspace; only then does the
    retryable host-loss failure carry that receipt. After the predecessor's
    volume is gone, the successor's separate workspace restores the bytes
    through the host runtime's existing checkpoint restore.
    """

    from moonmind.omnigent.execute import OmnigentSessionHostLostError
    from moonmind.omnigent.oauth_host_runtime import OmnigentOAuthHostRuntime
    from moonmind.omnigent.realizers.generic_host import carry_attempt_stop_evidence

    root = tmp_path / "worker"
    workspace, head = _candidate_workspace(root)
    blob_root = tmp_path / "durable-artifacts"
    monkeypatch.setattr(
        TemporalArtifactService,
        "_build_store_from_settings",
        staticmethod(lambda: LocalTemporalArtifactStore(blob_root)),
    )
    engine = create_async_engine("sqlite+aiosqlite://", poolclass=StaticPool)
    async with engine.begin() as connection:
        await connection.run_sync(Base.metadata.create_all)
    sessions = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    try:
        gateway = TemporalOmnigentArtifactGateway(session_factory=sessions)
        request = await _request(gateway)
        store = InMemoryStableRuntimeBindingStore()
        binding = await store.create_initial(
            execution_plan_ref=request.step_execution.omnigent_execution_plan.plan_ref,
            idempotency_key=request.idempotency_key,
            provider_leases={},
        )
        sink = RuntimeBindingSessionAuthoritySink(store, binding)
        await sink.record_phase(
            "workspace",
            request.model_dump(
                by_alias=True,
                mode="json",
                exclude_none=True,
                include={
                    "agent_kind",
                    "agent_id",
                    "correlation_id",
                    "idempotency_key",
                    "step_execution",
                },
            )
            | {"workspaceSpec": dict(request.workspace_spec)},
        )
        lost = OmnigentSessionHostLostError("host offline", offline_seconds=181.0)
        # Before stop is confirmed nothing is offered to a successor.
        carry_attempt_stop_evidence(lost, sink.binding)
        assert not hasattr(lost, "saved_workspace_checkpoint")

        publisher = OmnigentWorkspacePublicationService(root, artifact_gateway=gateway)
        realizer, _released = _owned_cleanup_realizer(store, publisher)
        cleaned, _host = await realizer._cleanup(
            request=request,
            binding=sink.binding,
            host_lease=None,
            host_context=None,
            prepared=None,
            credential_handles=(),
            acquired=(),
        )
        assert cleaned.state is RuntimeBindingState.cleaned
        assert "compute" not in cleaned.phaseResults

        carry_attempt_stop_evidence(lost, cleaned)
        saved = lost.saved_workspace_checkpoint
        assert saved == cleaned.phaseResults["saved"]

        # The old host and its volume are gone; the successor is a different
        # Step Execution with its own empty workspace.
        shutil.rmtree(root)
        # Like the successor's own materialization, start from a fresh
        # checkout of the base revision before applying the saved archive.
        successor = tmp_path / "successor" / "repo"
        successor.mkdir(parents=True)
        _git(successor, "init", "-q")
        _git(successor, "config", "user.name", "Journey")
        _git(successor, "config", "user.email", "journey@example.invalid")
        (successor / "app.py").write_text("print('base')\n")
        _git(successor, "add", ".")
        _git(successor, "commit", "-qm", "base")
        base = _git(successor, "rev-parse", "HEAD")
        runtime = OmnigentOAuthHostRuntime(
            client=SimpleNamespace(),
            workspace_root=tmp_path / "successor",
            repository_source_root=tmp_path,
        )
        await runtime._apply_workspace_checkpoint_restore(
            successor,
            artifact_ref=saved["archiveRef"],
            artifact_gateway=TemporalOmnigentArtifactGateway(session_factory=sessions),
        )

        assert (successor / "generated.py").read_text() == (
            "print('generated by the run')\n"
        )
        assert (successor / "app.py").read_text() == "print('uncommitted edit')\n"
        # The predecessor's unpublished commit survives as content on the
        # successor's base, not as preserved history.
        assert _git(successor, "rev-parse", "HEAD") == base != head
        assert _git(successor, "status", "--porcelain") == (
            "M app.py\n?? generated.py"
        )
    finally:
        await engine.dispose()


def test_saved_work_is_not_offered_without_confirmed_stop():
    from moonmind.omnigent.execute import OmnigentSessionHostLostError
    from moonmind.omnigent.realizers.generic_host import carry_attempt_stop_evidence

    saved = {"kind": "worktree_archive", "archiveRef": "artifact://art-a"}
    identity = {"executionPlanRef": "plan-a", "bindingId": "binding-a"}
    pending = SimpleNamespace(
        state=RuntimeBindingState.cleanup_pending,
        phaseResults={"saved": saved},
        **identity,
    )
    lost = OmnigentSessionHostLostError("host offline")
    carry_attempt_stop_evidence(lost, pending)
    assert not hasattr(lost, "saved_workspace_checkpoint")
    assert lost.unconfirmed_attempt_stop == {
        "executionPlanRef": "plan-a",
        "runtimeBindingRef": "binding-a",
        "bindingState": "cleanup_pending",
    }

    cleaned = SimpleNamespace(
        state=RuntimeBindingState.cleaned, phaseResults={"saved": saved}, **identity
    )
    # A cleanup error means the cleaned state was not this attempt's to trust.
    failed_cleanup = OmnigentSessionHostLostError("host offline")
    carry_attempt_stop_evidence(
        failed_cleanup, cleaned, cleanup_error=RuntimeError("late")
    )
    assert not hasattr(failed_cleanup, "saved_workspace_checkpoint")
    assert failed_cleanup.unconfirmed_attempt_stop["runtimeBindingRef"] == "binding-a"

    confirmed = OmnigentSessionHostLostError("host offline")
    carry_attempt_stop_evidence(confirmed, cleaned)
    assert confirmed.saved_workspace_checkpoint == saved
    assert not hasattr(confirmed, "unconfirmed_attempt_stop")


class _ReclaimableCredentials(_NoCredentials):
    async def load_cleanup_handles(self, provider_leases, runtime_handles):
        return ()


class _PartitionedHostRuntime:
    """A host whose stop acknowledgement is lost until the partition heals."""

    def __init__(self) -> None:
        self.partitioned = True
        self.stops: list[str] = []

    async def cleanup(self, *, host_context, host_lease_ref, host_lease_generation):
        if self.partitioned:
            raise ConnectionError("host stop acknowledgement lost")
        self.stops.append(host_lease_ref)
        return {"stopped": True}

    async def cleanup_authorities(self, refs):
        return None


async def _interrupted_attempt_with_unconfirmed_stop(tmp_path, monkeypatch, sessions):
    from moonmind.omnigent.execute import OmnigentSessionHostLostError
    from moonmind.omnigent.host_leases import InMemoryOmnigentHostLeaseRepository
    from moonmind.omnigent.realizers.generic_host import carry_attempt_stop_evidence

    root = tmp_path / "worker"
    _candidate_workspace(root)
    gateway = TemporalOmnigentArtifactGateway(session_factory=sessions)
    request = await _request(gateway)
    store = InMemoryStableRuntimeBindingStore()
    plan_ref = request.step_execution.omnigent_execution_plan.plan_ref
    binding = await store.create_initial(
        execution_plan_ref=plan_ref,
        idempotency_key=request.idempotency_key,
        provider_leases={},
    )
    host_leases = InMemoryOmnigentHostLeaseRepository()
    lease = await host_leases.acquire(
        execution_plan_ref=plan_ref,
        runtime_binding_id=binding.bindingId,
        host_class_ref="host-class:opencode",
        launch_policy_ref="policy",
        harness_id="opencode-native",
        harness_implementation_ref="opencode",
        provider_profile_refs=(),
    )
    lease = await host_leases.record_launch(
        lease.leaseRef,
        expected_generation=lease.generation,
        cleanup_handle={"containerName": "omnigent-host-old"},
    )
    binding = await store.update(
        binding.bindingId,
        expected_revision=binding.revision,
        expected_fencing_generation=binding.fencingGeneration,
        state=RuntimeBindingState.credentials_acquired,
        updates={"hostLeaseRef": lease.leaseRef},
    )
    sink = RuntimeBindingSessionAuthoritySink(store, binding)
    await sink.record_phase(
        "workspace",
        request.model_dump(
            by_alias=True,
            mode="json",
            exclude_none=True,
            include={
                "agent_kind",
                "agent_id",
                "correlation_id",
                "idempotency_key",
                "step_execution",
            },
        )
        | {"workspaceSpec": dict(request.workspace_spec)},
    )
    publisher = OmnigentWorkspacePublicationService(root, artifact_gateway=gateway)
    realizer, _released = _owned_cleanup_realizer(store, publisher)
    host_runtime = _PartitionedHostRuntime()
    realizer._host_runtime = host_runtime
    realizer._host_leases = host_leases
    realizer._credentials = _ReclaimableCredentials()
    released_from_binding: list = []

    async def release_from_binding(provider_leases):
        released_from_binding.append(provider_leases)

    realizer._provider_leases = SimpleNamespace(
        release_all=lambda acquired: _done(),
        release_from_binding=release_from_binding,
    )
    lost = OmnigentSessionHostLostError("host offline", offline_seconds=181.0)
    with pytest.raises(ConnectionError) as cleanup_error:
        await realizer._cleanup(
            request=request,
            binding=sink.binding,
            host_lease=lease,
            host_context=None,
            prepared=None,
            credential_handles=(),
            acquired=(),
        )
    stale = await store.get(binding.bindingId)
    carry_attempt_stop_evidence(lost, stale, cleanup_error=cleanup_error.value)
    return SimpleNamespace(
        lost=lost,
        store=store,
        stale=stale,
        realizer=realizer,
        host_runtime=host_runtime,
        host_leases=host_leases,
        lease=lease,
        plan_ref=plan_ref,
    )


@pytest.mark.asyncio
async def test_successor_waits_for_confirmed_stop_of_partitioned_predecessor(
    tmp_path, monkeypatch
):
    """A lost stop acknowledgement resumes that reconciliation, not parallel compute.

    #4627 R2: when the realizer could not confirm its interrupted attempt
    stopped, the failure offers no saved work to a successor, only the
    binding whose reconciliation is unfinished. The existing realizer
    reconciliation then fences the old owner, stops its host, and releases
    its capacity before a successor may write; late old-owner writes fail.
    """

    from moonmind.omnigent.generic_host_janitor import GenericOmnigentHostJanitor
    from moonmind.omnigent.harness_platform.failures import HarnessPlatformError

    blob_root = tmp_path / "durable-artifacts"
    monkeypatch.setattr(
        TemporalArtifactService,
        "_build_store_from_settings",
        staticmethod(lambda: LocalTemporalArtifactStore(blob_root)),
    )
    engine = create_async_engine("sqlite+aiosqlite://", poolclass=StaticPool)
    async with engine.begin() as connection:
        await connection.run_sync(Base.metadata.create_all)
    sessions = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    try:
        attempt = await _interrupted_attempt_with_unconfirmed_stop(
            tmp_path, monkeypatch, sessions
        )
        assert attempt.stale.state is RuntimeBindingState.cleanup_pending
        assert not hasattr(attempt.lost, "saved_workspace_checkpoint")
        assert attempt.lost.unconfirmed_attempt_stop == {
            "executionPlanRef": attempt.plan_ref,
            "runtimeBindingRef": attempt.stale.bindingId,
            "bindingState": "cleanup_pending",
        }

        owner_running = GenericOmnigentHostJanitor(
            host_leases=attempt.host_leases,
            runtime_bindings=attempt.store,
            realizer=attempt.realizer,
            owner_has_closed=lambda binding: _owner(False),
        )
        attempt.host_runtime.partitioned = False
        with pytest.raises(HarnessPlatformError) as running:
            await owner_running.confirm_attempt_stopped(
                execution_plan_ref=attempt.plan_ref,
                runtime_binding_ref=attempt.stale.bindingId,
            )
        assert running.value.code == "OMNIGENT_RUNTIME_BINDING_CONFLICT"
        assert attempt.host_runtime.stops == []

        janitor = GenericOmnigentHostJanitor(
            host_leases=attempt.host_leases,
            runtime_bindings=attempt.store,
            realizer=attempt.realizer,
            owner_has_closed=lambda binding: _owner(True),
        )
        confirmed = await janitor.confirm_attempt_stopped(
            execution_plan_ref=attempt.plan_ref,
            runtime_binding_ref=attempt.stale.bindingId,
        )
        cleaned = await attempt.store.get(attempt.stale.bindingId)
        assert cleaned.state is RuntimeBindingState.cleaned
        assert cleaned.fencingGeneration > attempt.stale.fencingGeneration
        assert attempt.host_runtime.stops == [attempt.lease.leaseRef]
        assert (await attempt.host_leases.get(attempt.lease.leaseRef)).status == (
            "cleaned"
        )
        assert confirmed["stopConfirmed"] is True
        assert confirmed["runtimeBindingRef"] == attempt.stale.bindingId
        saved = confirmed["savedWorkspaceCheckpoint"]
        assert saved == cleaned.phaseResults["saved"]
        assert saved["archiveRef"] and saved["archiveDigest"].startswith("sha256:")

        # A late write by the fenced old owner cannot change the binding.
        with pytest.raises(HarnessPlatformError):
            await attempt.store.update(
                attempt.stale.bindingId,
                expected_revision=attempt.stale.revision,
                expected_fencing_generation=attempt.stale.fencingGeneration,
                state=RuntimeBindingState.failed,
            )
        # Confirmation is idempotent for a redelivered request.
        again = await janitor.confirm_attempt_stopped(
            execution_plan_ref=attempt.plan_ref,
            runtime_binding_ref=attempt.stale.bindingId,
        )
        assert again == confirmed
        assert attempt.host_runtime.stops == [attempt.lease.leaseRef]
    finally:
        await engine.dispose()


async def _owner(closed: bool) -> bool:
    return closed
