"""Save before owned cleanup, then finish from saved bytes (MoonMind#4016).

The generic realizer's own cleanup and finalization owners drive the real
workspace publication service and production artifact gateway (sqlite plus a
local blob volume). After the owned workspace is removed, finalization
restores the exact saved candidate from its checkpoint without a provider
driver, a host, or any repository credential, and resumes only the phase that
had not finished.
"""

from __future__ import annotations

import asyncio
import hashlib
import shutil
import subprocess
from pathlib import Path
from types import SimpleNamespace

import pytest
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from api_service.db.models import Base
from moonmind.omnigent.bridge_artifacts import TemporalOmnigentArtifactGateway
from moonmind.omnigent.realizers.generic_host import GenericOmnigentHostRealizer
from moonmind.omnigent.runtime_bindings import (
    InMemoryStableRuntimeBindingStore,
    RuntimeBindingSessionAuthoritySink,
    RuntimeBindingState,
)
from moonmind.omnigent.workspace_publication import OmnigentWorkspacePublicationService
from moonmind.schemas.agent_runtime_models import (
    AgentExecutionRequest,
    AgentRunResult,
    OmnigentExecutionPlanBinding,
)
from moonmind.workflows.temporal.artifacts import (
    LocalTemporalArtifactStore,
    TemporalArtifactService,
)
from moonmind.workflows.temporal.runtime.workspace_locators import (
    SandboxWorkspaceRecord,
    SandboxWorkspaceRecordStore,
)

WORKFLOW_ID = "saved-finalization"
STEP_ID = f"{WORKFLOW_ID}:run-1:implement:execution:1"
WORKSPACE_ID = hashlib.sha256(f"{WORKFLOW_ID}:{STEP_ID}".encode()).hexdigest()[:24]


def _git(workspace: Path, *args: str) -> str:
    return subprocess.check_output(
        ["git", "-C", str(workspace), *args], text=True
    ).strip()


def _candidate_workspace(root: Path) -> tuple[Path, str]:
    workspace = root / "temporal_sandbox" / WORKSPACE_ID / "repo"
    workspace.mkdir(parents=True)
    _git(workspace, "init", "-q")
    _git(workspace, "config", "user.name", "Journey")
    _git(workspace, "config", "user.email", "journey@example.invalid")
    (workspace / "app.py").write_text("print('base')\n")
    _git(workspace, "add", ".")
    _git(workspace, "commit", "-qm", "base")
    # Generated work that never reached any remote.
    (workspace / "generated.py").write_text("print('generated by the run')\n")
    _git(workspace, "add", ".")
    _git(workspace, "commit", "-qm", "agent candidate")
    (workspace / "app.py").write_text("print('uncommitted edit')\n")
    SandboxWorkspaceRecordStore(root).ensure(
        SandboxWorkspaceRecord(WORKSPACE_ID, WORKFLOW_ID, STEP_ID, "repo")
    )
    return workspace, _git(workspace, "rev-parse", "HEAD")


async def _request(gateway: TemporalOmnigentArtifactGateway) -> AgentExecutionRequest:
    request = AgentExecutionRequest.model_validate(
        {
            "agentKind": "external",
            "agentId": "omnigent",
            "correlationId": WORKFLOW_ID,
            "idempotencyKey": "saved-finalization-attempt",
            "workspaceSpec": {
                "repository": "MoonLadderStudios/MoonMind",
                "workspaceLocator": {
                    "kind": "sandbox",
                    "workspaceId": WORKSPACE_ID,
                    "relativePath": "repo",
                },
            },
            "stepExecution": {
                "workflowId": WORKFLOW_ID,
                "runId": "run-1",
                "logicalStepId": "implement",
                "executionOrdinal": 1,
                "stepExecutionId": STEP_ID,
                "runtimeContextPolicy": "fresh_agent_run",
            },
        }
    )
    task_input = b'{"objective":"keep the generated candidate"}'
    plan = b'{"steps":["implement"]}'
    input_ref = await gateway.write_bytes(
        request=request,
        name="input",
        payload=task_input,
        content_type="application/json",
        link_type="input",
    )
    plan_ref = await gateway.write_bytes(
        request=request,
        name="plan",
        payload=plan,
        content_type="application/json",
        link_type="input",
    )
    digest = hashlib.sha256(plan).hexdigest()
    return request.model_copy(
        update={
            "step_execution": request.step_execution.model_copy(
                update={
                    "omnigent_execution_plan": OmnigentExecutionPlanBinding(
                        planRef="omnigent-execution-plan:sha256:" + digest,
                        planDigest="sha256:" + digest,
                        planArtifactRef=plan_ref,
                        taskInputSnapshotRef=input_ref,
                        taskInputSnapshotDigest="sha256:"
                        + hashlib.sha256(task_input).hexdigest(),
                    )
                }
            )
        }
    )


class _NoCredentials:
    async def cleanup_all(self, handles):
        return []

    def __getattr__(self, name):
        raise AttributeError(
            f"finalization must not use repository credentials: {name}"
        )


def _owned_cleanup_realizer(
    store, publisher
) -> tuple[GenericOmnigentHostRealizer, list]:
    realizer = object.__new__(GenericOmnigentHostRealizer)
    released: list = []
    realizer._runtime_bindings = store
    realizer._turn_commands = None
    realizer._cleanup_authority = None
    realizer._artifacts = None
    realizer._workspace_publisher = publisher
    realizer._session_cleanup = SimpleNamespace(drain=None)
    realizer._host_runtime = SimpleNamespace(
        cleanup_authorities=lambda refs: _done(), cleanup_prepared=None
    )
    realizer._credentials = _NoCredentials()

    async def release_all(acquired):
        released.append(tuple(acquired))

    realizer._provider_leases = SimpleNamespace(release_all=release_all)
    realizer._host_leases = SimpleNamespace()

    async def no_provider(*_args, **_kwargs):
        raise AssertionError("finalization must not start another agent run")

    realizer._session_driver = no_provider
    return realizer, released


async def _done():
    return None


@pytest.mark.asyncio
async def test_saved_candidate_survives_owned_cleanup_and_finishes_without_rerun(
    tmp_path, monkeypatch
):
    root = tmp_path / "worker"
    workspace, head = _candidate_workspace(root)
    blob_root = tmp_path / "durable-artifacts"
    monkeypatch.setattr(
        TemporalArtifactService,
        "_build_store_from_settings",
        staticmethod(lambda: LocalTemporalArtifactStore(blob_root)),
    )
    engine = create_async_engine("sqlite+aiosqlite://", poolclass=StaticPool)
    async with engine.begin() as connection:
        await connection.run_sync(Base.metadata.create_all)
    sessions = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    try:
        gateway = TemporalOmnigentArtifactGateway(session_factory=sessions)
        request = await _request(gateway)
        store = InMemoryStableRuntimeBindingStore()
        binding = await store.create_initial(
            execution_plan_ref=request.step_execution.omnigent_execution_plan.plan_ref,
            idempotency_key=request.idempotency_key,
            provider_leases={},
        )
        sink = RuntimeBindingSessionAuthoritySink(store, binding)
        await sink.record_phase(
            "workspace",
            request.model_dump(
                by_alias=True,
                mode="json",
                exclude_none=True,
                include={
                    "agent_kind",
                    "agent_id",
                    "correlation_id",
                    "idempotency_key",
                    "step_execution",
                },
            )
            | {"workspaceSpec": dict(request.workspace_spec)},
        )
        # Confirmed compute is durable before any later finalization error.
        await sink.record_phase(
            "compute",
            AgentRunResult(summary="candidate generated").model_dump(
                by_alias=True, mode="json", exclude_none=True
            ),
        )
        publisher = OmnigentWorkspacePublicationService(root, artifact_gateway=gateway)
        realizer, released = _owned_cleanup_realizer(store, publisher)

        cleaned, _host = await realizer._cleanup(
            request=request,
            binding=sink.binding,
            host_lease=None,
            host_context=None,
            prepared=None,
            credential_handles=(),
            acquired=("provider-lease",),
        )

        assert cleaned.state is RuntimeBindingState.cleaned
        assert released == [("provider-lease",)]
        saved = cleaned.phaseResults["saved"]
        assert "publication" not in cleaned.phaseResults
        # Committed, usable references: the bytes read back match the digest.
        archive = await gateway.read_bytes(saved["archiveRef"])
        assert "sha256:" + hashlib.sha256(archive).hexdigest() == saved["archiveDigest"]
        assert saved["checkpointRef"].startswith("artifact://art_")

        # The owned host and its workspace volume are gone.
        shutil.rmtree(root)
        published: list[AgentRunResult] = []

        async def publish(bound, result):
            restored = publisher.resolve_request_workspace(bound)
            assert _git(restored, "rev-parse", "HEAD") == head
            assert (restored / "generated.py").read_text() == (
                "print('generated by the run')\n"
            )
            assert (restored / "app.py").read_text() == "print('uncommitted edit')\n"
            published.append(result)
            return result.model_copy(update={"summary": "published saved candidate"})

        realizer._publish_repository = publish
        # A fresh replacement worker: new gateway and service, same durable state.
        replacement = OmnigentWorkspacePublicationService(
            root,
            artifact_gateway=TemporalOmnigentArtifactGateway(session_factory=sessions),
        )
        realizer._workspace_publisher = replacement
        realizer._interrupted_admission_result = lambda *_args: _done()

        # Two concurrent deliveries share one owner: one restore, one publish.
        first, second = await asyncio.gather(
            realizer._reconcile_finalization(
                request, await store.get(binding.bindingId)
            ),
            realizer._reconcile_finalization(
                request, await store.get(binding.bindingId)
            ),
        )

        assert first == second
        assert first.summary == "published saved candidate"
        assert first.metadata["savedWorkspaceCheckpoint"] == saved
        assert first.metadata["workPreserved"] is True
        assert len(published) == 1
        phases = (await store.get(binding.bindingId)).phaseResults
        assert phases["saved"] == saved
        assert phases["restoration"]["restorationEvidenceRef"]
    finally:
        await engine.dispose()


@pytest.mark.asyncio
async def test_host_lost_successor_restores_confirmed_saved_bytes(
    tmp_path, monkeypatch
):
    """An interrupted attempt's saved bytes reach a distinct successor (#4627).

    The turn never produced compute. The realizer's own cleanup confirms the
    predecessor stopped and saves its surviving workspace; only then does the
    retryable host-loss failure carry that receipt. After the predecessor's
    volume is gone, the successor's separate workspace restores the bytes
    through the host runtime's existing checkpoint restore.
    """

    from moonmind.omnigent.execute import OmnigentSessionHostLostError
    from moonmind.omnigent.oauth_host_runtime import OmnigentOAuthHostRuntime
    from moonmind.omnigent.realizers.generic_host import carry_confirmed_saved_work

    root = tmp_path / "worker"
    workspace, head = _candidate_workspace(root)
    blob_root = tmp_path / "durable-artifacts"
    monkeypatch.setattr(
        TemporalArtifactService,
        "_build_store_from_settings",
        staticmethod(lambda: LocalTemporalArtifactStore(blob_root)),
    )
    engine = create_async_engine("sqlite+aiosqlite://", poolclass=StaticPool)
    async with engine.begin() as connection:
        await connection.run_sync(Base.metadata.create_all)
    sessions = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    try:
        gateway = TemporalOmnigentArtifactGateway(session_factory=sessions)
        request = await _request(gateway)
        store = InMemoryStableRuntimeBindingStore()
        binding = await store.create_initial(
            execution_plan_ref=request.step_execution.omnigent_execution_plan.plan_ref,
            idempotency_key=request.idempotency_key,
            provider_leases={},
        )
        sink = RuntimeBindingSessionAuthoritySink(store, binding)
        await sink.record_phase(
            "workspace",
            request.model_dump(
                by_alias=True,
                mode="json",
                exclude_none=True,
                include={
                    "agent_kind",
                    "agent_id",
                    "correlation_id",
                    "idempotency_key",
                    "step_execution",
                },
            )
            | {"workspaceSpec": dict(request.workspace_spec)},
        )
        lost = OmnigentSessionHostLostError("host offline", offline_seconds=181.0)
        # Before stop is confirmed nothing is offered to a successor.
        carry_confirmed_saved_work(lost, sink.binding)
        assert not hasattr(lost, "saved_workspace_checkpoint")

        publisher = OmnigentWorkspacePublicationService(root, artifact_gateway=gateway)
        realizer, _released = _owned_cleanup_realizer(store, publisher)
        cleaned, _host = await realizer._cleanup(
            request=request,
            binding=sink.binding,
            host_lease=None,
            host_context=None,
            prepared=None,
            credential_handles=(),
            acquired=(),
        )
        assert cleaned.state is RuntimeBindingState.cleaned
        assert "compute" not in cleaned.phaseResults

        carry_confirmed_saved_work(lost, cleaned)
        saved = lost.saved_workspace_checkpoint
        assert saved == cleaned.phaseResults["saved"]

        # The old host and its volume are gone; the successor is a different
        # Step Execution with its own empty workspace.
        shutil.rmtree(root)
        # Like the successor's own materialization, start from a fresh
        # checkout of the base revision before applying the saved archive.
        successor = tmp_path / "successor" / "repo"
        successor.mkdir(parents=True)
        _git(successor, "init", "-q")
        _git(successor, "config", "user.name", "Journey")
        _git(successor, "config", "user.email", "journey@example.invalid")
        (successor / "app.py").write_text("print('base')\n")
        _git(successor, "add", ".")
        _git(successor, "commit", "-qm", "base")
        base = _git(successor, "rev-parse", "HEAD")
        runtime = OmnigentOAuthHostRuntime(
            client=SimpleNamespace(),
            workspace_root=tmp_path / "successor",
            repository_source_root=tmp_path,
        )
        await runtime._apply_workspace_checkpoint_restore(
            successor,
            artifact_ref=saved["archiveRef"],
            artifact_gateway=TemporalOmnigentArtifactGateway(session_factory=sessions),
        )

        assert (successor / "generated.py").read_text() == (
            "print('generated by the run')\n"
        )
        assert (successor / "app.py").read_text() == "print('uncommitted edit')\n"
        # The predecessor's unpublished commit survives as content on the
        # successor's base, not as preserved history.
        assert _git(successor, "rev-parse", "HEAD") == base != head
        assert _git(successor, "status", "--porcelain") == (
            "M app.py\n?? generated.py"
        )
    finally:
        await engine.dispose()


def test_saved_work_is_not_offered_without_confirmed_stop():
    from moonmind.omnigent.execute import OmnigentSessionHostLostError
    from moonmind.omnigent.realizers.generic_host import carry_confirmed_saved_work

    saved = {"kind": "worktree_archive", "archiveRef": "artifact://art-a"}
    pending = SimpleNamespace(
        state=RuntimeBindingState.cleanup_pending, phaseResults={"saved": saved}
    )
    lost = OmnigentSessionHostLostError("host offline")
    carry_confirmed_saved_work(lost, pending)
    assert not hasattr(lost, "saved_workspace_checkpoint")

    cleaned = SimpleNamespace(
        state=RuntimeBindingState.cleaned, phaseResults={"saved": saved}
    )
    carry_confirmed_saved_work(lost, cleaned)
    assert lost.saved_workspace_checkpoint == saved
