"""Shared service for publishing changes to repositories."""

from __future__ import annotations

import asyncio
import re
from pathlib import Path
from typing import Any, Awaitable, Callable, Protocol
from uuid import UUID

from moonmind.agents.codex_worker.utils import verify_cli_is_executable
from moonmind.publish.sanitization import (
    sanitize_metadata_footer_value,
    sanitize_publish_subject,
)


class CommandResult(Protocol):
    """Protocol for a command result with stdout."""

    @property
    def stdout(self) -> str: ...


CommandRunner = Callable[
    ...,
    Awaitable[CommandResult],
]


class PublishService:
    """Service to publish changes to Git branches or Pull Requests."""

    def __init__(
        self,
        *,
        git_binary: str = "git",
        gh_binary: str = "gh",
    ) -> None:
        self._git_binary = git_binary
        self._gh_binary = gh_binary

    @staticmethod
    def _extract_first_instruction_sentence(instruction: str) -> str | None:
        for line in str(instruction or "").splitlines():
            stripped = line.strip()
            if not stripped:
                continue
            first_sentence = stripped
            punctuation_match = re.search(r"[.!?]", stripped)
            if punctuation_match:
                first_sentence = stripped[: punctuation_match.end()]
            return " ".join(first_sentence.split())
        return None

    @classmethod
    def _sanitize_publish_subject(cls, value: str, *, max_chars: int) -> str:
        return sanitize_publish_subject(
            value,
            max_chars=max_chars,
            redact_uuids=True,
        )

    @staticmethod
    def _sanitize_metadata_footer_value(
        value: str | None, *, fallback: str = "unknown"
    ) -> str:
        return sanitize_metadata_footer_value(value, fallback=fallback)

    @classmethod
    def _derive_default_publish_subject(
        cls,
        *,
        instruction: str,
        max_chars: int,
    ) -> str:
        candidate = cls._extract_first_instruction_sentence(instruction)
        if candidate:
            return cls._sanitize_publish_subject(candidate, max_chars=max_chars)
        return cls._sanitize_publish_subject("Automated update", max_chars=max_chars)

    @classmethod
    def _derive_default_pr_body(
        cls,
        *,
        job_id: UUID,
        runtime_mode: str,
        base_branch: str,
        head_branch: str,
    ) -> str:
        runtime_value = cls._sanitize_metadata_footer_value(
            runtime_mode, fallback="codex"
        )
        base_value = cls._sanitize_metadata_footer_value(base_branch)
        head_value = cls._sanitize_metadata_footer_value(head_branch)
        lines = [
            "Automated PR generated by queue publish stage.",
            "",
            "---",
            "<!-- moonmind:begin -->",
            f"MoonMind Job: {job_id}",
            f"Runtime: {runtime_value}",
            f"Base: {base_value}",
            f"Head: {head_value}",
            "<!-- moonmind:end -->",
        ]
        return "\n".join(lines)

    async def publish(
        self,
        *,
        job_id: UUID,
        instruction: str,
        publish_mode: str,
        publish_base_branch: str | None,
        runtime_mode: str,
        repo_dir: Path,
        run_command: CommandRunner,
    ) -> str | None:
        """Publish the changes to a branch or a pull request.

        Args:
            job_id: The job identifier.
            instruction: The original instruction for the task.
            publish_mode: The publish mode ("none", "branch", "pr").
            publish_base_branch: Base branch to target for PRs (default: main).
            runtime_mode: The runtime that generated the changes (e.g. "codex", "claude").
            repo_dir: Path to the git repository.
            run_command: Async callable that runs a shell command and returns an object with a `stdout` attribute.
        """
        if publish_mode == "none":
            return None

        status = await run_command(
            [self._git_binary, "status", "--porcelain"],
            cwd=repo_dir,
            check=False,
        )
        if not status.stdout.strip():
            return "publish skipped: no local changes"

        branch_name = f"moonmind-job-{str(job_id)[:8]}"
        await run_command(
            [self._git_binary, "checkout", "-B", branch_name],
            cwd=repo_dir,
        )
        await run_command(
            [self._git_binary, "add", "-A"],
            cwd=repo_dir,
        )
        commit_message = self._derive_default_publish_subject(
            instruction=instruction,
            max_chars=72,
        )
        await run_command(
            [
                self._git_binary,
                "commit",
                "-m",
                commit_message,
            ],
            cwd=repo_dir,
            redaction_values=(commit_message,),
        )
        await run_command(
            [self._git_binary, "push", "-u", "origin", branch_name],
            cwd=repo_dir,
        )

        if publish_mode == "branch":
            return f"published branch {branch_name}"

        verify_cli_is_executable(self._gh_binary)
        base_branch = publish_base_branch or "main"
        pr_title = self._derive_default_publish_subject(
            instruction=instruction,
            max_chars=90,
        )
        pr_body = self._derive_default_pr_body(
            job_id=job_id,
            runtime_mode=runtime_mode,
            base_branch=base_branch,
            head_branch=branch_name,
        )
        await run_command(
            [
                self._gh_binary,
                "pr",
                "create",
                "--base",
                base_branch,
                "--head",
                branch_name,
                "--title",
                pr_title,
                "--body",
                pr_body,
            ],
            cwd=repo_dir,
            redaction_values=(pr_title, pr_body),
        )
        return f"published PR from {branch_name}"
