"""Shared service for publishing changes to repositories."""

from __future__ import annotations

import asyncio
import contextlib
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Awaitable, Callable, Literal, Protocol
from uuid import UUID

from moonmind.security.outbound_scan import (
    OutboundBundleItem,
    resolve_high_security_mode,
    scan_outbound_bundle,
)
from moonmind.workflows.adapters.github_service import GitHubService
from moonmind.utils.cli import verify_cli_is_executable
from moonmind.utils.logging import redact_sensitive_text
from moonmind.publish.sanitization import (
    sanitize_metadata_footer_value,
    sanitize_publish_subject,
)

class CommandResult(Protocol):
    """Protocol for a command result with stdout."""

    @property
    def stdout(self) -> str:
        pass

CommandRunner = Callable[
    ...,
    Awaitable[CommandResult],
]

@dataclass(frozen=True)
class PublishResult:
    mode: str
    status: Literal["published", "skipped", "failed"]
    reason_code: str | None = None
    reason: str | None = None
    commit_created: bool = False
    branch_pushed: bool = False
    pr_url: str | None = None
    branch_name: str | None = None

    def summary_text(self) -> str | None:
        if self.status == "skipped":
            return self.reason
        if self.status != "published":
            return self.reason
        if self.pr_url:
            return f"published PR {self.pr_url}"
        if self.mode == "pr" and self.branch_name:
            return f"published PR from {self.branch_name}"
        if self.branch_name:
            return f"published branch {self.branch_name}"
        return self.reason

_PUBLISH_PUSH_SCAN_MAX_COMMIT_METADATA_CHARS = 100_000
_PUBLISH_PUSH_SCAN_MAX_FILE_DIFF_CHARS = 200_000
_PUBLISH_PUSH_SCAN_MAX_CHANGED_FILES = 200

class PublishService:
    """Service to publish changes to Git branches or Pull Requests."""

    def __init__(
        self,
        *,
        git_binary: str = "git",
        gh_binary: str = "gh",
        github_create_pull_request: Callable[..., Awaitable[Any]] | None = None,
    ) -> None:
        self._git_binary = git_binary
        self._gh_binary = gh_binary
        self._github_create_pull_request = github_create_pull_request

    @staticmethod
    def _extract_first_instruction_sentence(instruction: str) -> str | None:
        for line in str(instruction or "").splitlines():
            stripped = line.strip()
            if not stripped:
                continue
            first_sentence = stripped
            punctuation_match = re.search(r"[.!?]", stripped)
            if punctuation_match:
                first_sentence = stripped[: punctuation_match.end()]
            return " ".join(first_sentence.split())
        return None

    @classmethod
    def _sanitize_publish_subject(cls, value: str, *, max_chars: int) -> str:
        return sanitize_publish_subject(
            value,
            max_chars=max_chars,
            redact_uuids=True,
        )

    @staticmethod
    def _sanitize_metadata_footer_value(
        value: str | None, *, fallback: str = "unknown"
    ) -> str:
        return sanitize_metadata_footer_value(value, fallback=fallback)

    @classmethod
    def _derive_default_publish_subject(
        cls,
        *,
        instruction: str,
        max_chars: int,
    ) -> str:
        candidate = cls._extract_first_instruction_sentence(instruction)
        if candidate:
            return cls._sanitize_publish_subject(candidate, max_chars=max_chars)
        return cls._sanitize_publish_subject("Automated update", max_chars=max_chars)

    @classmethod
    def _derive_default_pr_body(
        cls,
        *,
        job_id: UUID,
        runtime_mode: str,
        base_branch: str,
        head_branch: str,
    ) -> str:
        runtime_value = cls._sanitize_metadata_footer_value(
            runtime_mode, fallback="codex"
        )
        base_value = cls._sanitize_metadata_footer_value(base_branch)
        head_value = cls._sanitize_metadata_footer_value(head_branch)
        lines = [
            "Automated PR generated by queue publish stage.",
            "",
            "---",
            "<!-- moonmind:begin -->",
            f"MoonMind Job: {job_id}",
            f"Runtime: {runtime_value}",
            f"Base: {base_value}",
            f"Head: {head_value}",
            "<!-- moonmind:end -->",
        ]
        return "\n".join(lines)

    async def publish(
        self,
        *,
        job_id: UUID,
        instruction: str,
        publish_mode: str,
        publish_base_branch: str | None,
        runtime_mode: str,
        repo_dir: Path,
        run_command: CommandRunner,
        repo: str | None = None,
    ) -> PublishResult | None:
        """Publish the changes to a branch or a pull request.

        Args:
            job_id: The job identifier.
            instruction: The original instruction for the task.
            publish_mode: The publish mode ("auto", "none", "branch", "pr").
            publish_base_branch: Base branch to target for PRs (default: main).
            runtime_mode: The runtime that generated the changes (e.g. "codex", "claude").
            repo_dir: Path to the git repository.
            run_command: Async callable that runs a shell command and returns an object with a `stdout` attribute.
        """
        if publish_mode == "none":
            return None

        status = await run_command(
            [self._git_binary, "status", "--porcelain"],
            cwd=repo_dir,
            check=False,
        )
        if not status.stdout.strip():
            return PublishResult(
                mode=publish_mode,
                status="skipped",
                reason_code="no_commit",
                reason="No repository changes were available to commit or publish.",
            )

        branch_name = f"moonmind-job-{str(job_id)[:8]}"
        await run_command(
            [self._git_binary, "checkout", "-B", branch_name],
            cwd=repo_dir,
        )
        await run_command(
            [self._git_binary, "add", "-A"],
            cwd=repo_dir,
        )
        commit_message = self._derive_default_publish_subject(
            instruction=instruction,
            max_chars=72,
        )
        await run_command(
            [
                self._git_binary,
                "commit",
                "-m",
                commit_message,
            ],
            cwd=repo_dir,
            redaction_values=(commit_message,),
        )
        commit_created = True
        await self._scan_git_push_before_publish(
            repo_dir=repo_dir,
            branch_name=branch_name,
            base_ref=f"origin/{publish_base_branch or 'main'}",
            env={**os.environ, "GIT_TERMINAL_PROMPT": "0"},
        )
        token = ""
        push_env = {**os.environ, "GIT_TERMINAL_PROMPT": "0"}
        resolved_github_credential = None
        if repo:
            from moonmind.auth.github_credentials import resolve_github_credential

            resolved_github_credential = await resolve_github_credential(repo=repo)
            token = resolved_github_credential.token or ""
            if token:
                push_env["GITHUB_TOKEN"] = token
                push_env["GH_TOKEN"] = token
        await run_command(
            [self._git_binary, "push", "-u", "origin", branch_name],
            cwd=repo_dir,
            env=push_env,
            redaction_values=(token,) if token else (),
        )
        branch_pushed = True

        if publish_mode == "branch":
            return PublishResult(
                mode=publish_mode,
                status="published",
                reason=f"published branch {branch_name}",
                commit_created=commit_created,
                branch_pushed=branch_pushed,
                branch_name=branch_name,
            )

        base_branch = publish_base_branch or "main"
        pr_title = self._derive_default_publish_subject(
            instruction=instruction,
            max_chars=90,
        )
        pr_body = self._derive_default_pr_body(
            job_id=job_id,
            runtime_mode=runtime_mode,
            base_branch=base_branch,
            head_branch=branch_name,
        )
        if repo and token:
            create_pull_request = (
                self._github_create_pull_request
                or GitHubService().create_pull_request
            )
            result = await create_pull_request(
                repo=repo,
                head=branch_name,
                base=base_branch,
                title=pr_title,
                body=pr_body,
                github_token=token,
            )
            if not getattr(result, "created", False):
                summary = getattr(result, "summary", "GitHub create PR failed.")
                raise RuntimeError(str(summary))
            url = getattr(result, "url", None)
            return PublishResult(
                mode=publish_mode,
                status="published",
                reason=(
                    f"published PR {url}"
                    if url
                    else f"published PR from {branch_name}"
                ),
                commit_created=commit_created,
                branch_pushed=branch_pushed,
                pr_url=str(url) if url else None,
                branch_name=branch_name,
            )

        if resolved_github_credential is None:
            from moonmind.auth.github_credentials import resolve_github_credential

            resolved_github_credential = await resolve_github_credential()
            token = resolved_github_credential.token or ""
        if not token:
            raise RuntimeError(
                "GitHub CLI PR fallback requires an explicit resolved token; "
                "ambient gh auth state is not a managed publishing contract. "
                f"{resolved_github_credential.safe_summary}"
            )

        verify_cli_is_executable(self._gh_binary)
        gh_env = {**os.environ, "GIT_TERMINAL_PROMPT": "0"}
        gh_env["GITHUB_TOKEN"] = token
        gh_env["GH_TOKEN"] = token
        if repo:
            gh_env["GH_REPO"] = repo
        await run_command(
            [
                self._gh_binary,
                "pr",
                "create",
                "--base",
                base_branch,
                "--head",
                branch_name,
                "--title",
                pr_title,
                "--body",
                pr_body,
            ],
            cwd=repo_dir,
            env=gh_env,
            redaction_values=tuple(
                value for value in (pr_title, pr_body, token) if value
            ),
        )
        return PublishResult(
            mode=publish_mode,
            status="published",
            reason=f"published PR from {branch_name}",
            commit_created=commit_created,
            branch_pushed=branch_pushed,
            branch_name=branch_name,
        )

    async def _scan_git_push_before_publish(
        self,
        *,
        repo_dir: Path,
        branch_name: str,
        base_ref: str,
        env: dict[str, str],
    ) -> None:
        if not resolve_high_security_mode():
            return

        if base_ref.startswith("origin/"):
            with contextlib.suppress(Exception):
                await self._read_git_text_for_scan(
                    repo_dir=repo_dir,
                    env=env,
                    timeout=30,
                    args=["fetch", "origin", base_ref.removeprefix("origin/")],
                )
        commit_range = f"{base_ref}..{branch_name}"
        try:
            commit_metadata = await self._read_git_text_for_scan(
                repo_dir=repo_dir,
                env=env,
                timeout=15,
                args=[
                    "log",
                    (
                        "--format=commit %H%nparents %P%nauthor %an <%ae>%n"
                        + "subject %s%nbody%n%B%n---END-COMMIT---"
                    ),
                    commit_range,
                ],
            )
            changed_files_text = await self._read_git_text_for_scan(
                repo_dir=repo_dir,
                env=env,
                timeout=15,
                args=["diff", "--name-only", commit_range],
            )
            bundle = [
                OutboundBundleItem(
                    location=f"git.push.commits:{commit_range}",
                    content=commit_metadata[
                        :_PUBLISH_PUSH_SCAN_MAX_COMMIT_METADATA_CHARS
                    ],
                )
            ]
            changed_files = [
                line.strip()
                for line in changed_files_text.splitlines()
                if line.strip()
            ][:_PUBLISH_PUSH_SCAN_MAX_CHANGED_FILES]
            diff_semaphore = asyncio.Semaphore(10)

            async def _diff_item(changed_file: str) -> OutboundBundleItem:
                async with diff_semaphore:
                    file_diff = await self._read_git_text_for_scan(
                        repo_dir=repo_dir,
                        env=env,
                        timeout=20,
                        args=[
                            "diff",
                            "--no-ext-diff",
                            commit_range,
                            "--",
                            changed_file,
                        ],
                    )
                return OutboundBundleItem(
                    location=f"git.push.diff:{changed_file}",
                    content=file_diff[:_PUBLISH_PUSH_SCAN_MAX_FILE_DIFF_CHARS],
                )

            bundle.extend(
                await asyncio.gather(*(_diff_item(path) for path in changed_files))
            )
        except Exception as exc:
            safe_detail = redact_sensitive_text(str(exc))
            raise RuntimeError(
                "outbound git push blocked: could not build high security "
                f"scan payload for {commit_range}: {safe_detail}"
            ) from exc

        scan_result = scan_outbound_bundle(bundle, high_security_mode=True)
        if scan_result.allowed:
            return
        diagnostics = "; ".join(scan_result.sanitized_diagnostics)
        raise RuntimeError(
            "outbound git push blocked by high security scan: " + diagnostics
        )

    async def _read_git_text_for_scan(
        self,
        *,
        repo_dir: Path,
        env: dict[str, str],
        timeout: int,
        args: list[str],
    ) -> str:
        proc = await asyncio.create_subprocess_exec(
            self._git_binary,
            "-C",
            str(repo_dir),
            *args,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )
        try:
            stdout_bytes, stderr_bytes = await asyncio.wait_for(
                proc.communicate(), timeout=timeout,
            )
        except asyncio.TimeoutError:
            proc.kill()
            await proc.wait()
            raise
        if proc.returncode != 0:
            detail = (
                stderr_bytes.decode("utf-8", errors="replace").strip()
                or stdout_bytes.decode("utf-8", errors="replace").strip()
                or f"git exited with {proc.returncode}"
            )
            raise RuntimeError(detail)
        return stdout_bytes.decode("utf-8", errors="replace")
