"""update_provider_profiles_schema

Revision ID: 053758f254f3
Revises: 4b53a4790314
Create Date: 2026-03-27 00:03:59.699780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = '053758f254f3'
down_revision: Union[str, None] = '4b53a4790314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('managed_agent_oauth_sessions', 'auth_mode',
               existing_type=postgresql.ENUM('oauth', 'api_key', name='managedagentauthmode'),
               type_=sa.Enum('oauth_volume', 'secret_ref', 'none', name='providercredentialsource'),
               existing_nullable=False,
               existing_server_default=sa.text("'oauth'::managedagentauthmode"))
    op.add_column('managed_agent_provider_profiles', sa.Column('provider_id', sa.String(length=64), server_default=sa.text("'unknown'"), nullable=False))
    op.add_column('managed_agent_provider_profiles', sa.Column('provider_label', sa.String(length=255), nullable=True))
    op.add_column('managed_agent_provider_profiles', sa.Column('credential_source', sa.Enum('oauth_volume', 'secret_ref', 'none', name='providercredentialsource'), server_default='none', nullable=False))
    op.add_column('managed_agent_provider_profiles', sa.Column('runtime_materialization_mode', sa.Enum('oauth_home', 'api_key_env', 'env_bundle', 'config_bundle', 'composite', name='runtimematerializationmode'), server_default='composite', nullable=False))
    op.add_column('managed_agent_provider_profiles', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('managed_agent_provider_profiles', sa.Column('priority', sa.Integer(), server_default=sa.text('100'), nullable=False))
    op.add_column('managed_agent_provider_profiles', sa.Column('secret_refs', sa.JSON(), nullable=True))
    op.add_column('managed_agent_provider_profiles', sa.Column('clear_env_keys', sa.JSON(), nullable=True))
    op.add_column('managed_agent_provider_profiles', sa.Column('env_template', sa.JSON(), nullable=True))
    op.add_column('managed_agent_provider_profiles', sa.Column('file_templates', sa.JSON(), nullable=True))
    op.add_column('managed_agent_provider_profiles', sa.Column('home_path_overrides', sa.JSON(), nullable=True))
    op.add_column('managed_agent_provider_profiles', sa.Column('command_behavior', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_auth_profiles_enabled'), table_name='managed_agent_provider_profiles')
    op.drop_index(op.f('ix_auth_profiles_runtime'), table_name='managed_agent_provider_profiles')
    op.create_index('ix_provider_profiles_enabled', 'managed_agent_provider_profiles', ['enabled'], unique=False)
    op.create_index('ix_provider_profiles_provider', 'managed_agent_provider_profiles', ['provider_id'], unique=False)
    op.create_index('ix_provider_profiles_runtime', 'managed_agent_provider_profiles', ['runtime_id'], unique=False)
    
    # --- Data Migration ---
    op.execute(
        "UPDATE managed_agent_provider_profiles SET "
        "credential_source = CASE WHEN auth_mode = 'oauth' THEN 'oauth_volume'::providercredentialsource ELSE 'secret_ref'::providercredentialsource END, "
        "runtime_materialization_mode = CASE WHEN auth_mode = 'oauth' THEN 'oauth_home'::runtimematerializationmode ELSE 'env_bundle'::runtimematerializationmode END, "
        "provider_id = CASE WHEN runtime_id = 'gemini_cli' THEN 'google' WHEN runtime_id = 'codex_cli' THEN 'moonladder' WHEN runtime_id = 'claude_code' THEN 'anthropic' ELSE 'unknown' END;"
    )

    op.drop_column('managed_agent_provider_profiles', 'auth_mode')
    op.drop_column('managed_agent_provider_profiles', 'api_key_ref')
    op.drop_column('managed_agent_provider_profiles', 'runtime_env_overrides')
    op.drop_column('managed_agent_provider_profiles', 'api_key_env_var')
    op.drop_index(op.f('ix_slot_leases_runtime'), table_name='provider_profile_slot_leases')
    op.drop_index(op.f('ix_slot_leases_workflow'), table_name='provider_profile_slot_leases')
    op.drop_constraint(op.f('uq_slot_lease_runtime_workflow'), 'provider_profile_slot_leases', type_='unique')
    op.create_index('ix_provider_slot_leases_runtime', 'provider_profile_slot_leases', ['runtime_id'], unique=False)
    op.create_index('ix_provider_slot_leases_workflow', 'provider_profile_slot_leases', ['workflow_id'], unique=False)
    op.create_unique_constraint('uq_provider_slot_lease_runtime_workflow', 'provider_profile_slot_leases', ['runtime_id', 'workflow_id'])
    op.alter_column('task_run_live_sessions', 'attach_rw_encrypted',
               existing_type=sa.TEXT(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=True)
    op.alter_column('task_run_live_sessions', 'web_rw_encrypted',
               existing_type=sa.TEXT(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=True)
    op.alter_column('user_profile', 'google_api_key_encrypted',
               existing_type=postgresql.BYTEA(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=True)
    op.alter_column('user_profile', 'openai_api_key_encrypted',
               existing_type=postgresql.BYTEA(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=True)
    op.alter_column('user_profile', 'github_token_encrypted',
               existing_type=postgresql.BYTEA(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=True)
    op.alter_column('user_profile', 'anthropic_api_key_encrypted',
               existing_type=postgresql.BYTEA(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'anthropic_api_key_encrypted',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.alter_column('user_profile', 'github_token_encrypted',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.alter_column('user_profile', 'openai_api_key_encrypted',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.alter_column('user_profile', 'google_api_key_encrypted',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.alter_column('task_run_live_sessions', 'web_rw_encrypted',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('task_run_live_sessions', 'attach_rw_encrypted',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_provider_slot_lease_runtime_workflow', 'provider_profile_slot_leases', type_='unique')
    op.drop_index('ix_provider_slot_leases_workflow', table_name='provider_profile_slot_leases')
    op.drop_index('ix_provider_slot_leases_runtime', table_name='provider_profile_slot_leases')
    op.create_unique_constraint(op.f('uq_slot_lease_runtime_workflow'), 'provider_profile_slot_leases', ['runtime_id', 'workflow_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_slot_leases_workflow'), 'provider_profile_slot_leases', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_slot_leases_runtime'), 'provider_profile_slot_leases', ['runtime_id'], unique=False)
    op.add_column('managed_agent_provider_profiles', sa.Column('api_key_env_var', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('managed_agent_provider_profiles', sa.Column('runtime_env_overrides', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('managed_agent_provider_profiles', sa.Column('api_key_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('managed_agent_provider_profiles', sa.Column('auth_mode', postgresql.ENUM('oauth', 'api_key', name='managedagentauthmode'), autoincrement=False, nullable=False))
    op.drop_index('ix_provider_profiles_runtime', table_name='managed_agent_provider_profiles')
    op.drop_index('ix_provider_profiles_provider', table_name='managed_agent_provider_profiles')
    op.drop_index('ix_provider_profiles_enabled', table_name='managed_agent_provider_profiles')
    op.create_index(op.f('ix_auth_profiles_runtime'), 'managed_agent_provider_profiles', ['runtime_id'], unique=False)
    op.create_index(op.f('ix_auth_profiles_enabled'), 'managed_agent_provider_profiles', ['enabled'], unique=False)
    op.drop_column('managed_agent_provider_profiles', 'command_behavior')
    op.drop_column('managed_agent_provider_profiles', 'home_path_overrides')
    op.drop_column('managed_agent_provider_profiles', 'file_templates')
    op.drop_column('managed_agent_provider_profiles', 'env_template')
    op.drop_column('managed_agent_provider_profiles', 'clear_env_keys')
    op.drop_column('managed_agent_provider_profiles', 'secret_refs')
    op.drop_column('managed_agent_provider_profiles', 'priority')
    op.drop_column('managed_agent_provider_profiles', 'tags')
    op.drop_column('managed_agent_provider_profiles', 'runtime_materialization_mode')
    op.drop_column('managed_agent_provider_profiles', 'credential_source')
    op.drop_column('managed_agent_provider_profiles', 'provider_label')
    op.drop_column('managed_agent_provider_profiles', 'provider_id')
    op.alter_column('managed_agent_oauth_sessions', 'auth_mode',
               existing_type=sa.Enum('oauth_volume', 'secret_ref', 'none', name='providercredentialsource'),
               type_=postgresql.ENUM('oauth', 'api_key', name='managedagentauthmode'),
               existing_nullable=False,
               existing_server_default=sa.text("'oauth'::managedagentauthmode"))
    # ### end Alembic commands ###
