"""Initial clean migration

Revision ID: 0b8e4befb8e5
Revises: 
Create Date: 2026-03-28 18:39:57.978384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b8e4befb8e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('base_branch', sa.String(length=128), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('pull_request_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('queued', 'in_progress', 'completed', 'failed', 'no_changes', name='specautomationrunstatus'), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('requested_spec_input', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_hostname', sa.String(length=255), nullable=True),
    sa.Column('job_container_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automation_runs_created_at', 'automation_runs', ['created_at'], unique=False)
    op.create_index('ix_automation_runs_external_ref', 'automation_runs', ['external_ref'], unique=False)
    op.create_index('ix_automation_runs_repository', 'automation_runs', ['repository'], unique=False)
    op.create_index('ix_automation_runs_status', 'automation_runs', ['status'], unique=False)
    op.create_table('codex_auth_volumes',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('worker_affinity', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ready', 'needs_auth', 'error', name='codexauthvolumestatus'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('worker_affinity', name='uq_codex_auth_volumes_worker_affinity')
    )
    op.create_table('managed_agent_oauth_sessions',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('runtime_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=128), nullable=False),
    sa.Column('auth_mode', sa.Enum('oauth_volume', 'secret_ref', 'none', name='providercredentialsource'), server_default='oauth_volume', nullable=False),
    sa.Column('session_transport', sa.String(length=64), server_default=sa.text("'none'"), nullable=False),
    sa.Column('volume_ref', sa.String(length=255), nullable=True),
    sa.Column('volume_mount_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('pending', 'starting', 'oauth_runner_ready', 'awaiting_user', 'verifying', 'registering_profile', 'succeeded', 'failed', 'cancelled', 'expired', name='oauthsessionstatus'), server_default='pending', nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=128), nullable=True),
    sa.Column('account_label', sa.String(length=255), nullable=True),
    sa.Column('oauth_web_url', sa.String(length=1024), nullable=True),
    sa.Column('oauth_ssh_url', sa.String(length=1024), nullable=True),
    sa.Column('container_name', sa.String(length=255), nullable=True),
    sa.Column('worker_service', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=1024), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_oauth_sessions_profile', 'managed_agent_oauth_sessions', ['profile_id'], unique=False)
    op.create_index('ix_oauth_sessions_status', 'managed_agent_oauth_sessions', ['status'], unique=False)
    op.create_table('managed_agent_provider_profiles',
    sa.Column('profile_id', sa.String(length=128), nullable=False),
    sa.Column('runtime_id', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=64), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('provider_label', sa.String(length=255), nullable=True),
    sa.Column('credential_source', sa.Enum('oauth_volume', 'secret_ref', 'none', name='providercredentialsource'), server_default='none', nullable=False),
    sa.Column('runtime_materialization_mode', sa.Enum('oauth_home', 'api_key_env', 'env_bundle', 'config_bundle', 'composite', name='runtimematerializationmode'), server_default='composite', nullable=False),
    sa.Column('account_label', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('volume_ref', sa.String(length=255), nullable=True),
    sa.Column('volume_mount_path', sa.String(length=512), nullable=True),
    sa.Column('secret_refs', sa.JSON(), nullable=True),
    sa.Column('clear_env_keys', sa.JSON(), nullable=True),
    sa.Column('env_template', sa.JSON(), nullable=True),
    sa.Column('file_templates', sa.JSON(), nullable=True),
    sa.Column('home_path_overrides', sa.JSON(), nullable=True),
    sa.Column('command_behavior', sa.JSON(), nullable=True),
    sa.Column('max_parallel_runs', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('cooldown_after_429_seconds', sa.Integer(), server_default=sa.text('900'), nullable=False),
    sa.Column('rate_limit_policy', sa.Enum('backoff', 'queue', 'fail_fast', name='managedagentratelimitpolicy'), server_default='backoff', nullable=False),
    sa.Column('max_lease_duration_seconds', sa.Integer(), server_default=sa.text('7200'), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index('ix_provider_profiles_enabled', 'managed_agent_provider_profiles', ['enabled'], unique=False)
    op.create_index('ix_provider_profiles_provider', 'managed_agent_provider_profiles', ['provider_id'], unique=False)
    op.create_index('ix_provider_profiles_runtime', 'managed_agent_provider_profiles', ['runtime_id'], unique=False)
    op.create_table('managed_secrets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('ciphertext', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', 'rotated', 'deleted', 'invalid', name='secretstatus'), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_managed_secrets_slug', 'managed_secrets', ['slug'], unique=True)
    op.create_index('ix_managed_secrets_status', 'managed_secrets', ['status'], unique=False)
    op.create_table('manifest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=32), server_default='v0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_job_id', sa.Uuid(), nullable=True),
    sa.Column('last_run_source', sa.String(length=16), nullable=True),
    sa.Column('last_run_status', sa.String(length=32), nullable=True),
    sa.Column('last_run_workflow_id', sa.String(length=64), nullable=True),
    sa.Column('last_run_temporal_run_id', sa.String(length=64), nullable=True),
    sa.Column('last_run_manifest_ref', sa.String(length=512), nullable=True),
    sa.Column('last_run_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('state_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_manifest_id'), 'manifest', ['id'], unique=False)
    op.create_table('provider_profile_slot_leases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('runtime_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.String(length=128), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runtime_id', 'workflow_id', name='uq_provider_slot_lease_runtime_workflow')
    )
    op.create_index('ix_provider_slot_leases_runtime', 'provider_profile_slot_leases', ['runtime_id'], unique=False)
    op.create_index('ix_provider_slot_leases_workflow', 'provider_profile_slot_leases', ['workflow_id'], unique=False)
    op.create_table('task_run_live_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_run_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('none', name='agentjoblivesessionprovider'), nullable=False),
    sa.Column('status', sa.Enum('disabled', 'starting', 'ready', 'revoked', 'ended', 'error', name='agentjoblivesessionstatus'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('worker_hostname', sa.String(length=255), nullable=True),
    sa.Column('live_session_name', sa.String(length=255), nullable=True),
    sa.Column('live_session_socket_path', sa.String(length=1024), nullable=True),
    sa.Column('attach_ro', sa.Text(), nullable=True),
    sa.Column('attach_rw_encrypted', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('web_ro', sa.Text(), nullable=True),
    sa.Column('web_rw_encrypted', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('rw_granted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_run_live_sessions_last_heartbeat_at'), 'task_run_live_sessions', ['last_heartbeat_at'], unique=False)
    op.create_index('ix_task_run_live_sessions_status_expires_at', 'task_run_live_sessions', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_task_run_live_sessions_task_run_id'), 'task_run_live_sessions', ['task_run_id'], unique=True)
    op.create_index(op.f('ix_task_run_live_sessions_worker_id'), 'task_run_live_sessions', ['worker_id'], unique=False)
    op.create_table('task_source_mappings',
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('entry', sa.String(length=32), nullable=True),
    sa.Column('source_record_id', sa.String(length=128), nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('owner_type', sa.String(length=32), nullable=True),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('ix_task_source_mappings_source_entry', 'task_source_mappings', ['source', 'entry'], unique=False)
    op.create_index('ix_task_source_mappings_source_record_id', 'task_source_mappings', ['source', 'source_record_id'], unique=False)
    op.create_table('temporal_artifacts',
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_principal', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=128), nullable=True),
    sa.Column('storage_backend', sa.Enum('s3', 'local_fs', name='temporalartifactstoragebackend'), server_default='s3', nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('encryption', sa.Enum('sse-kms', 'sse-s3', 'none', 'envelope', name='temporalartifactencryption'), server_default='none', nullable=False),
    sa.Column('status', sa.Enum('pending_upload', 'complete', 'failed', 'deleted', name='temporalartifactstatus'), server_default='pending_upload', nullable=False),
    sa.Column('retention_class', sa.Enum('ephemeral', 'standard', 'long', 'pinned', name='temporalartifactretentionclass'), server_default='standard', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redaction_level', sa.Enum('none', 'preview_only', 'restricted', name='temporalartifactredactionlevel'), server_default='none', nullable=False),
    sa.Column('upload_mode', sa.Enum('single_put', 'multipart', name='temporalartifactuploadmode'), server_default='single_put', nullable=False),
    sa.Column('upload_id', sa.String(length=255), nullable=True),
    sa.Column('upload_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hard_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tombstoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_lifecycle_run_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('artifact_id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_temporal_artifacts_created_at', 'temporal_artifacts', ['created_at'], unique=False)
    op.create_index('ix_temporal_artifacts_deleted_at', 'temporal_artifacts', ['deleted_at'], unique=False)
    op.create_index('ix_temporal_artifacts_expires_at', 'temporal_artifacts', ['expires_at'], unique=False)
    op.create_index('ix_temporal_artifacts_hard_deleted_at', 'temporal_artifacts', ['hard_deleted_at'], unique=False)
    op.create_index('ix_temporal_artifacts_status', 'temporal_artifacts', ['status'], unique=False)
    op.create_table('temporal_execution_sources',
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('workflow_type', sa.Enum('MoonMind.Run', 'MoonMind.ManifestIngest', 'MoonMind.ProviderProfileManager', name='temporalworkflowtype'), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('owner_type', sa.Enum('user', 'system', 'service', name='temporalexecutionownertype'), server_default='user', nullable=False),
    sa.Column('state', sa.Enum('scheduled', 'initializing', 'waiting_on_dependencies', 'planning', 'awaiting_slot', 'executing', 'proposals', 'awaiting_external', 'finalizing', 'completed', 'failed', 'canceled', name='moonmindworkflowstate'), server_default='initializing', nullable=False),
    sa.Column('close_status', sa.Enum('completed', 'failed', 'canceled', 'terminated', 'timed_out', 'continued_as_new', name='temporalexecutionclosestatus'), nullable=True),
    sa.Column('entry', sa.String(length=16), nullable=False),
    sa.Column('search_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('memo', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('artifact_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_ref', sa.String(length=512), nullable=True),
    sa.Column('plan_ref', sa.String(length=512), nullable=True),
    sa.Column('manifest_ref', sa.String(length=512), nullable=True),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('integration_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('pending_parameters_patch', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('awaiting_external', sa.Boolean(), nullable=False),
    sa.Column('waiting_reason', sa.String(length=32), nullable=True),
    sa.Column('attention_required', sa.Boolean(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('wait_cycle_count', sa.Integer(), nullable=False),
    sa.Column('rerun_count', sa.Integer(), nullable=False),
    sa.Column('create_idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('last_update_idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('last_update_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('workflow_id'),
    sa.UniqueConstraint('create_idempotency_key', 'owner_id', 'owner_type', 'workflow_type', name='uq_temporal_execution_sources_create_idempotency_owner_type')
    )
    op.create_index('ix_temporal_execution_sources_owner_state', 'temporal_execution_sources', ['owner_id', 'state'], unique=False)
    op.create_index('ix_temporal_execution_sources_state_updated_at', 'temporal_execution_sources', ['state', 'updated_at'], unique=False)
    op.create_index('ix_temporal_execution_sources_type_updated_at', 'temporal_execution_sources', ['workflow_type', 'updated_at'], unique=False)
    op.create_table('temporal_executions',
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('workflow_type', sa.Enum('MoonMind.Run', 'MoonMind.ManifestIngest', 'MoonMind.ProviderProfileManager', name='temporalworkflowtype'), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('owner_type', sa.Enum('user', 'system', 'service', name='temporalexecutionownertype'), server_default='user', nullable=False),
    sa.Column('state', sa.Enum('scheduled', 'initializing', 'waiting_on_dependencies', 'planning', 'awaiting_slot', 'executing', 'proposals', 'awaiting_external', 'finalizing', 'completed', 'failed', 'canceled', name='moonmindworkflowstate'), server_default='initializing', nullable=False),
    sa.Column('close_status', sa.Enum('completed', 'failed', 'canceled', 'terminated', 'timed_out', 'continued_as_new', name='temporalexecutionclosestatus'), nullable=True),
    sa.Column('entry', sa.String(length=16), nullable=False),
    sa.Column('search_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('memo', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('artifact_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_ref', sa.String(length=512), nullable=True),
    sa.Column('plan_ref', sa.String(length=512), nullable=True),
    sa.Column('manifest_ref', sa.String(length=512), nullable=True),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('integration_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('pending_parameters_patch', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('awaiting_external', sa.Boolean(), nullable=False),
    sa.Column('waiting_reason', sa.String(length=32), nullable=True),
    sa.Column('attention_required', sa.Boolean(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('wait_cycle_count', sa.Integer(), nullable=False),
    sa.Column('rerun_count', sa.Integer(), nullable=False),
    sa.Column('create_idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('last_update_idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('last_update_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('projection_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_state', sa.Enum('fresh', 'stale', 'repair_pending', 'orphaned', name='temporalexecutionprojectionsyncstate'), server_default='fresh', nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('source_mode', sa.Enum('projection_only', 'mixed', 'temporal_authoritative', name='temporalexecutionprojectionsourcemode'), server_default='projection_only', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('workflow_id'),
    sa.UniqueConstraint('create_idempotency_key', 'owner_id', 'owner_type', 'workflow_type', name='uq_temporal_executions_create_idempotency_owner_type')
    )
    op.create_index('ix_temporal_executions_owner_state', 'temporal_executions', ['owner_id', 'state'], unique=False)
    op.create_index('ix_temporal_executions_state_updated_at', 'temporal_executions', ['state', 'updated_at'], unique=False)
    op.create_index('ix_temporal_executions_type_updated_at', 'temporal_executions', ['workflow_type', 'updated_at'], unique=False)
    op.create_table('user',
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('oidc_provider', sa.String(length=32), nullable=True),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oidc_provider', 'oidc_subject', name='uq_oidc_identity')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_oidc_provider'), 'user', ['oidc_provider'], unique=False)
    op.create_index(op.f('ix_user_oidc_subject'), 'user', ['oidc_subject'], unique=False)
    op.create_table('automation_agent_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_backend', sa.String(length=128), nullable=False),
    sa.Column('agent_version', sa.String(length=128), nullable=False),
    sa.Column('prompt_pack_version', sa.String(length=128), nullable=True),
    sa.Column('runtime_env', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['automation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_automation_agent_config_run')
    )
    op.create_table('automation_task_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.Enum('prepare_job', 'start_job_container', 'git_clone', 'speckit_specify', 'speckit_plan', 'speckit_tasks', 'speckit_analyze', 'speckit_implement', 'commit_push', 'open_pr', 'cleanup', name='specautomationphase'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', 'retrying', name='specautomationtaskstatus'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stdout_path', sa.String(length=1024), nullable=True),
    sa.Column('stderr_path', sa.String(length=1024), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['automation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'phase', 'attempt', name='uq_automation_task_state_attempt')
    )
    op.create_index('ix_automation_task_states_run_id', 'automation_task_states', ['run_id'], unique=False)
    op.create_table('codex_worker_shards',
    sa.Column('queue_name', sa.String(length=64), nullable=False),
    sa.Column('volume_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'draining', 'offline', name='codexworkershardstatus'), nullable=False),
    sa.Column('hash_modulo', sa.Integer(), nullable=False),
    sa.Column('worker_hostname', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['volume_name'], ['codex_auth_volumes.name'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('queue_name'),
    sa.UniqueConstraint('volume_name', name='uq_codex_worker_shards_volume_name')
    )
    op.create_table('recurring_task_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.Enum('cron', name='recurringtaskscheduletype'), nullable=False),
    sa.Column('cron', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=128), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_dispatch_status', sa.String(length=32), nullable=True),
    sa.Column('last_dispatch_error', sa.Text(), nullable=True),
    sa.Column('temporal_schedule_id', sa.String(length=255), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('scope_type', sa.Enum('personal', 'global', name='recurringtaskscopetype'), nullable=False),
    sa.Column('scope_ref', sa.String(length=255), nullable=True),
    sa.Column('target', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recurring_task_definitions_enabled_next_run_at', 'recurring_task_definitions', ['enabled', 'next_run_at'], unique=False)
    op.create_index('ix_recurring_task_definitions_owner_enabled', 'recurring_task_definitions', ['owner_user_id', 'enabled'], unique=False)
    op.create_table('task_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('open', 'promoted', 'dismissed', 'accepted', 'rejected', name='taskproposalstatus'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('dedup_key', sa.String(length=512), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('review_priority', sa.Enum('low', 'normal', 'high', 'urgent', name='taskproposalpriority'), nullable=False),
    sa.Column('priority_override_reason', sa.Text(), nullable=True),
    sa.Column('task_create_request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('proposed_by_worker_id', sa.String(length=255), nullable=True),
    sa.Column('proposed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('origin_source', sa.Enum('queue', 'workflow', 'manual', name='taskproposaloriginsource'), nullable=False),
    sa.Column('origin_id', sa.Uuid(), nullable=True),
    sa.Column('origin_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promoted_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_proposals_dedup_hash_status', 'task_proposals', ['dedup_hash', 'status'], unique=False)
    op.create_index('ix_task_proposals_origin', 'task_proposals', ['origin_source', 'origin_id'], unique=False)
    op.create_index('ix_task_proposals_priority_created', 'task_proposals', ['review_priority', 'created_at'], unique=False)
    op.create_index('ix_task_proposals_repository', 'task_proposals', ['repository'], unique=False)
    op.create_index('ix_task_proposals_status_created', 'task_proposals', ['status', 'created_at'], unique=False)
    op.create_table('task_step_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('scope_type', sa.Enum('global', 'personal', name='tasktemplatescopetype'), nullable=False),
    sa.Column('scope_ref', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('required_capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('latest_version_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['latest_version_id'], ['task_step_template_versions.id'], name='fk_task_template_latest_version', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'scope_type', 'scope_ref', name='uq_task_step_template_slug_scope')
    )
    op.create_index('ix_task_step_templates_active', 'task_step_templates', ['is_active'], unique=False)
    op.create_index('ix_task_step_templates_scope', 'task_step_templates', ['scope_type', 'scope_ref'], unique=False)
    op.create_index('ix_task_step_templates_slug', 'task_step_templates', ['slug'], unique=False)
    op.create_table('temporal_artifact_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('link_type', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_activity_type', sa.String(length=255), nullable=True),
    sa.Column('created_by_worker', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['temporal_artifacts.artifact_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temporal_artifact_links_artifact_id', 'temporal_artifact_links', ['artifact_id'], unique=False)
    op.create_index('ix_temporal_artifact_links_execution', 'temporal_artifact_links', ['namespace', 'workflow_id', 'run_id', 'link_type', 'created_at'], unique=False)
    op.create_table('temporal_artifact_pins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('pinned_by_principal', sa.String(length=255), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['temporal_artifacts.artifact_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', name='uq_temporal_artifact_pins_artifact_id')
    )
    op.create_table('temporal_integration_correlations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_name', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('callback_correlation_key', sa.String(length=128), nullable=True),
    sa.Column('external_operation_id', sa.String(length=255), nullable=True),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['temporal_executions.workflow_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_name', 'callback_correlation_key', name='uq_temporal_integration_correlations_callback_key'),
    sa.UniqueConstraint('integration_name', 'external_operation_id', name='uq_temporal_integration_correlations_operation_id')
    )
    op.create_index('ix_temporal_integration_correlations_workflow_status', 'temporal_integration_correlations', ['workflow_id', 'lifecycle_status'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('google_api_key_encrypted', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('openai_api_key_encrypted', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('github_token_encrypted', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('anthropic_api_key_encrypted', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=False)
    op.create_table('automation_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('task_state_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.Enum('stdout_log', 'stderr_log', 'diff_summary', 'commit_status', 'metrics_snapshot', 'environment_info', name='specautomationartifacttype'), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_phase', sa.Enum('prepare_job', 'start_job_container', 'git_clone', 'speckit_specify', 'speckit_plan', 'speckit_tasks', 'speckit_analyze', 'speckit_implement', 'commit_push', 'open_pr', 'cleanup', name='specautomationphase'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['automation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_state_id'], ['automation_task_states.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'artifact_type', 'storage_path', name='uq_automation_artifact_path')
    )
    op.create_index('ix_automation_artifacts_run_id', 'automation_artifacts', ['run_id'], unique=False)
    op.create_table('recurring_task_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger', sa.Enum('schedule', 'manual', name='recurringtaskruntrigger'), nullable=False),
    sa.Column('outcome', sa.Enum('pending_dispatch', 'enqueued', 'skipped', 'dispatch_error', name='recurringtaskrunoutcome'), nullable=False),
    sa.Column('dispatch_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dispatch_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temporal_workflow_id', sa.String(length=128), nullable=True),
    sa.Column('temporal_run_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['recurring_task_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_id', 'scheduled_for', name='uq_recurring_task_runs_definition_scheduled_for')
    )
    op.create_index('ix_recurring_task_runs_definition_created_at', 'recurring_task_runs', ['definition_id', 'created_at'], unique=False)
    op.create_index('ix_recurring_task_runs_outcome_dispatch_after', 'recurring_task_runs', ['outcome', 'dispatch_after'], unique=False)
    op.create_table('task_proposal_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['task_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'target', name='uq_task_proposal_notifications_proposal_target')
    )
    op.create_table('task_step_template_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['task_step_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'template_id', name='uq_task_template_favorite')
    )
    op.create_index('ix_task_step_template_favorites_user', 'task_step_template_favorites', ['user_id'], unique=False)
    op.create_table('task_step_template_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('inputs_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('annotations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('required_capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('max_step_count', sa.Integer(), nullable=False),
    sa.Column('release_status', sa.Enum('draft', 'active', 'inactive', name='tasktemplatereleasestatus'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('seed_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['task_step_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uq_task_step_template_version_label')
    )
    op.create_index('ix_task_step_template_versions_template', 'task_step_template_versions', ['template_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feature_key', sa.String(length=255), nullable=False),
    sa.Column('legacy_chain_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'no_work', 'cancelled', 'retrying', name='specworkflowrunstatus'), nullable=False),
    sa.Column('phase', sa.Enum('discover', 'submit', 'apply', 'publish', 'complete', name='specworkflowrunphase'), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('repository', sa.String(length=255), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('codex_task_id', sa.String(length=255), nullable=True),
    sa.Column('codex_queue', sa.String(length=64), nullable=True),
    sa.Column('codex_volume', sa.String(length=64), nullable=True),
    sa.Column('codex_preflight_status', sa.Enum('pending', 'passed', 'failed', 'skipped', name='codexpreflightstatus'), nullable=True),
    sa.Column('codex_preflight_message', sa.Text(), nullable=True),
    sa.Column('codex_logs_path', sa.String(length=1024), nullable=True),
    sa.Column('codex_patch_path', sa.String(length=1024), nullable=True),
    sa.Column('artifacts_path', sa.String(length=512), nullable=True),
    sa.Column('current_task_name', sa.Enum('discover', 'submit', 'apply', 'publish', 'finalize', 'retry-hook', name='specworkflowtaskname'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['codex_queue'], ['codex_worker_shards.queue_name'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['codex_volume'], ['codex_auth_volumes.name'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_runs_created_by', 'workflow_runs', ['created_by'], unique=False)
    op.create_index('ix_workflow_runs_feature_key', 'workflow_runs', ['feature_key'], unique=False)
    op.create_index('ix_workflow_runs_requested_by', 'workflow_runs', ['requested_by_user_id'], unique=False)
    op.create_index('ix_workflow_runs_status', 'workflow_runs', ['status'], unique=False)
    op.create_table('task_step_template_recents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_version_id'], ['task_step_template_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'template_version_id', name='uq_task_template_recent_user_version')
    )
    op.create_index('ix_task_step_template_recents_user', 'task_step_template_recents', ['user_id'], unique=False)
    op.create_table('workflow_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_run_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.Enum('codex_logs', 'codex_patch', 'gh_push_log', 'gh_pr_response', 'apply_output', 'pr_payload', 'retry_context', name='workflowartifacttype'), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('digest', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_run_id', 'artifact_type', 'path', name='uq_workflow_artifact_path')
    )
    op.create_index('ix_workflow_artifacts_run_id', 'workflow_artifacts', ['workflow_run_id'], unique=False)
    op.create_table('workflow_credential_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_run_id', sa.Uuid(), nullable=False),
    sa.Column('codex_status', sa.Enum('valid', 'invalid', 'expires_soon', name='workflowcodexcredentialstatus'), nullable=False),
    sa.Column('github_status', sa.Enum('valid', 'invalid', 'scope_missing', name='workflowgithubcredentialstatus'), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('codex_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('codex_message', sa.Text(), nullable=True),
    sa.Column('github_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_message', sa.Text(), nullable=True),
    sa.Column('environment_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_run_id', name='uq_workflow_credential_audit_run')
    )
    op.create_index('ix_workflow_credential_audits_run', 'workflow_credential_audits', ['workflow_run_id'], unique=False)
    op.create_table('workflow_task_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_run_id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'skipped', name='specworkflowtaskstatus'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('worker_task_id', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('artifact_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('task_name IS NOT NULL', name='ck_workflow_task_state_task_name_required'),
    sa.CheckConstraint('workflow_run_id IS NOT NULL', name='ck_workflow_task_state_workflow_run_required'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_run_id', 'task_name', 'attempt', name='uq_workflow_task_state_attempt')
    )
    op.create_index('ix_workflow_task_states_failed', 'workflow_task_states', ['workflow_run_id'], unique=False, postgresql_where=sa.text("status = 'failed'"))
    op.create_index('ix_workflow_task_states_run_id', 'workflow_task_states', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_task_states_run_id', table_name='workflow_task_states')
    op.drop_index('ix_workflow_task_states_failed', table_name='workflow_task_states', postgresql_where=sa.text("status = 'failed'"))
    op.drop_table('workflow_task_states')
    op.drop_index('ix_workflow_credential_audits_run', table_name='workflow_credential_audits')
    op.drop_table('workflow_credential_audits')
    op.drop_index('ix_workflow_artifacts_run_id', table_name='workflow_artifacts')
    op.drop_table('workflow_artifacts')
    op.drop_index('ix_task_step_template_recents_user', table_name='task_step_template_recents')
    op.drop_table('task_step_template_recents')
    op.drop_index('ix_workflow_runs_status', table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_requested_by', table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_feature_key', table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_created_by', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index('ix_task_step_template_versions_template', table_name='task_step_template_versions')
    op.drop_table('task_step_template_versions')
    op.drop_index('ix_task_step_template_favorites_user', table_name='task_step_template_favorites')
    op.drop_table('task_step_template_favorites')
    op.drop_table('task_proposal_notifications')
    op.drop_index('ix_recurring_task_runs_outcome_dispatch_after', table_name='recurring_task_runs')
    op.drop_index('ix_recurring_task_runs_definition_created_at', table_name='recurring_task_runs')
    op.drop_table('recurring_task_runs')
    op.drop_index('ix_automation_artifacts_run_id', table_name='automation_artifacts')
    op.drop_table('automation_artifacts')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index('ix_temporal_integration_correlations_workflow_status', table_name='temporal_integration_correlations')
    op.drop_table('temporal_integration_correlations')
    op.drop_table('temporal_artifact_pins')
    op.drop_index('ix_temporal_artifact_links_execution', table_name='temporal_artifact_links')
    op.drop_index('ix_temporal_artifact_links_artifact_id', table_name='temporal_artifact_links')
    op.drop_table('temporal_artifact_links')
    op.drop_index('ix_task_step_templates_slug', table_name='task_step_templates')
    op.drop_index('ix_task_step_templates_scope', table_name='task_step_templates')
    op.drop_index('ix_task_step_templates_active', table_name='task_step_templates')
    op.drop_table('task_step_templates')
    op.drop_index('ix_task_proposals_status_created', table_name='task_proposals')
    op.drop_index('ix_task_proposals_repository', table_name='task_proposals')
    op.drop_index('ix_task_proposals_priority_created', table_name='task_proposals')
    op.drop_index('ix_task_proposals_origin', table_name='task_proposals')
    op.drop_index('ix_task_proposals_dedup_hash_status', table_name='task_proposals')
    op.drop_table('task_proposals')
    op.drop_index('ix_recurring_task_definitions_owner_enabled', table_name='recurring_task_definitions')
    op.drop_index('ix_recurring_task_definitions_enabled_next_run_at', table_name='recurring_task_definitions')
    op.drop_table('recurring_task_definitions')
    op.drop_table('codex_worker_shards')
    op.drop_index('ix_automation_task_states_run_id', table_name='automation_task_states')
    op.drop_table('automation_task_states')
    op.drop_table('automation_agent_configs')
    op.drop_index(op.f('ix_user_oidc_subject'), table_name='user')
    op.drop_index(op.f('ix_user_oidc_provider'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index('ix_temporal_executions_type_updated_at', table_name='temporal_executions')
    op.drop_index('ix_temporal_executions_state_updated_at', table_name='temporal_executions')
    op.drop_index('ix_temporal_executions_owner_state', table_name='temporal_executions')
    op.drop_table('temporal_executions')
    op.drop_index('ix_temporal_execution_sources_type_updated_at', table_name='temporal_execution_sources')
    op.drop_index('ix_temporal_execution_sources_state_updated_at', table_name='temporal_execution_sources')
    op.drop_index('ix_temporal_execution_sources_owner_state', table_name='temporal_execution_sources')
    op.drop_table('temporal_execution_sources')
    op.drop_index('ix_temporal_artifacts_status', table_name='temporal_artifacts')
    op.drop_index('ix_temporal_artifacts_hard_deleted_at', table_name='temporal_artifacts')
    op.drop_index('ix_temporal_artifacts_expires_at', table_name='temporal_artifacts')
    op.drop_index('ix_temporal_artifacts_deleted_at', table_name='temporal_artifacts')
    op.drop_index('ix_temporal_artifacts_created_at', table_name='temporal_artifacts')
    op.drop_table('temporal_artifacts')
    op.drop_index('ix_task_source_mappings_source_record_id', table_name='task_source_mappings')
    op.drop_index('ix_task_source_mappings_source_entry', table_name='task_source_mappings')
    op.drop_table('task_source_mappings')
    op.drop_index(op.f('ix_task_run_live_sessions_worker_id'), table_name='task_run_live_sessions')
    op.drop_index(op.f('ix_task_run_live_sessions_task_run_id'), table_name='task_run_live_sessions')
    op.drop_index('ix_task_run_live_sessions_status_expires_at', table_name='task_run_live_sessions')
    op.drop_index(op.f('ix_task_run_live_sessions_last_heartbeat_at'), table_name='task_run_live_sessions')
    op.drop_table('task_run_live_sessions')
    op.drop_index('ix_provider_slot_leases_workflow', table_name='provider_profile_slot_leases')
    op.drop_index('ix_provider_slot_leases_runtime', table_name='provider_profile_slot_leases')
    op.drop_table('provider_profile_slot_leases')
    op.drop_index(op.f('ix_manifest_id'), table_name='manifest')
    op.drop_table('manifest')
    op.drop_index('ix_managed_secrets_status', table_name='managed_secrets')
    op.drop_index('ix_managed_secrets_slug', table_name='managed_secrets')
    op.drop_table('managed_secrets')
    op.drop_index('ix_provider_profiles_runtime', table_name='managed_agent_provider_profiles')
    op.drop_index('ix_provider_profiles_provider', table_name='managed_agent_provider_profiles')
    op.drop_index('ix_provider_profiles_enabled', table_name='managed_agent_provider_profiles')
    op.drop_table('managed_agent_provider_profiles')
    op.drop_index('ix_oauth_sessions_status', table_name='managed_agent_oauth_sessions')
    op.drop_index('ix_oauth_sessions_profile', table_name='managed_agent_oauth_sessions')
    op.drop_table('managed_agent_oauth_sessions')
    op.drop_table('codex_auth_volumes')
    op.drop_index('ix_automation_runs_status', table_name='automation_runs')
    op.drop_index('ix_automation_runs_repository', table_name='automation_runs')
    op.drop_index('ix_automation_runs_external_ref', table_name='automation_runs')
    op.drop_index('ix_automation_runs_created_at', table_name='automation_runs')
    op.drop_table('automation_runs')
    # ### end Alembic commands ###
