"""add_github_token_to_user_profile

Revision ID: 1f2c8c5d4d3e
Revises: 1b4d0f8a3c0a
Create Date: 2025-11-06 00:00:00.000000

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "1f2c8c5d4d3e"
down_revision = "1b4d0f8a3c0a"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from api_service.core.encryption import get_encryption_key

    op.add_column(
        "user_profile",
        sa.Column(
            "github_token_encrypted",
            sqlalchemy_utils.EncryptedType(sa.Text, get_encryption_key),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "github_token_encrypted")
    # ### end Alembic commands ###
