"""add_github_token_to_user_profile

Revision ID: 1f2c8c5d4d3e
Revises: 9e9bd65e1b9e
Create Date: 2025-11-06 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f2c8c5d4d3e"
down_revision: Union[str, None] = "9e9bd65e1b9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profile",
        sa.Column(
            "github_token_encrypted",
            sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(sa.Text),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "github_token_encrypted")
    # ### end Alembic commands ###
