"""add_openai_api_key

Revision ID: 33e4b7073b5d
Revises: 05c60c95ba1b
Create Date: 2024-07-26 10:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33e4b7073b5d"
down_revision: Union[str, None] = "05c60c95ba1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profile",
        sa.Column(
            "openai_api_key_encrypted",
            sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(sa.Text),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "openai_api_key_encrypted")
    # ### end Alembic commands ###
