"""Add owner_user_id to managed_agent_auth_profiles

Revision ID: 3b27177de0fe
Revises: f1b2c3d4e5f6
Create Date: 2026-03-21 21:50:59.657242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b27177de0fe'
down_revision: Union[str, None] = 'f1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_agent_auth_profiles', sa.Column('owner_user_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managed_agent_auth_profiles', 'owner_user_id')
    # ### end Alembic commands ###
