"""Initial clean migration

Revision ID: 594fc88de6eb
Revises: 
Create Date: 2026-03-18 20:58:13.351962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import api_service
import fastapi_users_db_sqlalchemy
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '594fc88de6eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_worker_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('allowed_repositories', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('allowed_job_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('runtime_capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_agent_worker_tokens_created_at', 'agent_worker_tokens', ['created_at'], unique=False)
    op.create_index('ix_agent_worker_tokens_is_active', 'agent_worker_tokens', ['is_active'], unique=False)
    op.create_index('ix_agent_worker_tokens_worker_id', 'agent_worker_tokens', ['worker_id'], unique=False)
    op.create_table('approval_gates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('requirement', sa.Enum('none', 'pre-run', 'pre-verify', name='orchestratorapprovalrequirement'), server_default='none', nullable=False),
    sa.Column('approver_roles', api_service.db.models.ApproverRoleListType(sa.String(length=128)), nullable=False),
    sa.Column('valid_for_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_for_minutes >= 5', name='ck_approval_gates_min_duration'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name', name='uq_approval_gates_service_name')
    )
    op.create_table('automation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('base_branch', sa.String(length=128), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('pull_request_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('queued', 'in_progress', 'succeeded', 'failed', 'no_changes', name='specautomationrunstatus'), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('requested_spec_input', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_hostname', sa.String(length=255), nullable=True),
    sa.Column('job_container_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automation_runs_created_at', 'automation_runs', ['created_at'], unique=False)
    op.create_index('ix_automation_runs_external_ref', 'automation_runs', ['external_ref'], unique=False)
    op.create_index('ix_automation_runs_repository', 'automation_runs', ['repository'], unique=False)
    op.create_index('ix_automation_runs_status', 'automation_runs', ['status'], unique=False)
    op.create_table('codex_auth_volumes',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('worker_affinity', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ready', 'needs_auth', 'error', name='codexauthvolumestatus'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('worker_affinity', name='uq_codex_auth_volumes_worker_affinity')
    )
    op.create_table('managed_agent_auth_profiles',
    sa.Column('profile_id', sa.String(length=128), nullable=False),
    sa.Column('runtime_id', sa.String(length=64), nullable=False),
    sa.Column('auth_mode', sa.Enum('oauth', 'api_key', name='managedagentauthmode'), nullable=False),
    sa.Column('volume_ref', sa.String(length=255), nullable=True),
    sa.Column('volume_mount_path', sa.String(length=512), nullable=True),
    sa.Column('account_label', sa.String(length=255), nullable=True),
    sa.Column('api_key_ref', sa.String(length=255), nullable=True),
    sa.Column('max_parallel_runs', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('cooldown_after_429_seconds', sa.Integer(), server_default=sa.text('300'), nullable=False),
    sa.Column('rate_limit_policy', sa.Enum('backoff', 'queue', 'fail_fast', name='managedagentratelimitpolicy'), server_default='backoff', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index('ix_auth_profiles_enabled', 'managed_agent_auth_profiles', ['enabled'], unique=False)
    op.create_index('ix_auth_profiles_runtime', 'managed_agent_auth_profiles', ['runtime_id'], unique=False)
    op.create_table('manifest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=32), server_default='v0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_job_id', sa.Uuid(), nullable=True),
    sa.Column('last_run_source', sa.String(length=16), nullable=True),
    sa.Column('last_run_status', sa.String(length=32), nullable=True),
    sa.Column('last_run_workflow_id', sa.String(length=64), nullable=True),
    sa.Column('last_run_temporal_run_id', sa.String(length=64), nullable=True),
    sa.Column('last_run_manifest_ref', sa.String(length=512), nullable=True),
    sa.Column('last_run_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('state_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_manifest_id'), 'manifest', ['id'], unique=False)
    op.create_table('orchestrator_action_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('service_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.Enum('operator', 'llm', 'system', name='orchestratorplanorigin'), server_default='system', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_source_mappings',
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('entry', sa.String(length=32), nullable=True),
    sa.Column('source_record_id', sa.String(length=128), nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('owner_type', sa.String(length=32), nullable=True),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('ix_task_source_mappings_source_entry', 'task_source_mappings', ['source', 'entry'], unique=False)
    op.create_index('ix_task_source_mappings_source_record_id', 'task_source_mappings', ['source', 'source_record_id'], unique=False)
    op.create_table('temporal_artifacts',
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_principal', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=128), nullable=True),
    sa.Column('storage_backend', sa.Enum('s3', 'local_fs', name='temporalartifactstoragebackend'), server_default='s3', nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('encryption', sa.Enum('sse-kms', 'sse-s3', 'none', 'envelope', name='temporalartifactencryption'), server_default='none', nullable=False),
    sa.Column('status', sa.Enum('pending_upload', 'complete', 'failed', 'deleted', name='temporalartifactstatus'), server_default='pending_upload', nullable=False),
    sa.Column('retention_class', sa.Enum('ephemeral', 'standard', 'long', 'pinned', name='temporalartifactretentionclass'), server_default='standard', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redaction_level', sa.Enum('none', 'preview_only', 'restricted', name='temporalartifactredactionlevel'), server_default='none', nullable=False),
    sa.Column('upload_mode', sa.Enum('single_put', 'multipart', name='temporalartifactuploadmode'), server_default='single_put', nullable=False),
    sa.Column('upload_id', sa.String(length=255), nullable=True),
    sa.Column('upload_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hard_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tombstoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_lifecycle_run_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('artifact_id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_temporal_artifacts_created_at', 'temporal_artifacts', ['created_at'], unique=False)
    op.create_index('ix_temporal_artifacts_deleted_at', 'temporal_artifacts', ['deleted_at'], unique=False)
    op.create_index('ix_temporal_artifacts_expires_at', 'temporal_artifacts', ['expires_at'], unique=False)
    op.create_index('ix_temporal_artifacts_hard_deleted_at', 'temporal_artifacts', ['hard_deleted_at'], unique=False)
    op.create_index('ix_temporal_artifacts_status', 'temporal_artifacts', ['status'], unique=False)
    op.create_table('temporal_execution_sources',
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('workflow_type', sa.Enum('MoonMind.Run', 'MoonMind.ManifestIngest', 'MoonMind.AuthProfileManager', name='temporalworkflowtype'), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('owner_type', sa.Enum('user', 'system', 'service', name='temporalexecutionownertype'), server_default='user', nullable=False),
    sa.Column('state', sa.Enum('initializing', 'planning', 'executing', 'awaiting_external', 'finalizing', 'succeeded', 'failed', 'canceled', name='moonmindworkflowstate'), server_default='initializing', nullable=False),
    sa.Column('close_status', sa.Enum('completed', 'failed', 'canceled', 'terminated', 'timed_out', 'continued_as_new', name='temporalexecutionclosestatus'), nullable=True),
    sa.Column('entry', sa.String(length=16), nullable=False),
    sa.Column('search_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('memo', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('artifact_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_ref', sa.String(length=512), nullable=True),
    sa.Column('plan_ref', sa.String(length=512), nullable=True),
    sa.Column('manifest_ref', sa.String(length=512), nullable=True),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('integration_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('pending_parameters_patch', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('awaiting_external', sa.Boolean(), nullable=False),
    sa.Column('waiting_reason', sa.String(length=32), nullable=True),
    sa.Column('attention_required', sa.Boolean(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('wait_cycle_count', sa.Integer(), nullable=False),
    sa.Column('rerun_count', sa.Integer(), nullable=False),
    sa.Column('create_idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('last_update_idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('last_update_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('workflow_id'),
    sa.UniqueConstraint('create_idempotency_key', 'owner_id', 'owner_type', 'workflow_type', name='uq_temporal_execution_sources_create_idempotency_owner_type')
    )
    op.create_index('ix_temporal_execution_sources_owner_state', 'temporal_execution_sources', ['owner_id', 'state'], unique=False)
    op.create_index('ix_temporal_execution_sources_state_updated_at', 'temporal_execution_sources', ['state', 'updated_at'], unique=False)
    op.create_index('ix_temporal_execution_sources_type_updated_at', 'temporal_execution_sources', ['workflow_type', 'updated_at'], unique=False)
    op.create_table('temporal_executions',
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('workflow_type', sa.Enum('MoonMind.Run', 'MoonMind.ManifestIngest', 'MoonMind.AuthProfileManager', name='temporalworkflowtype'), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('owner_type', sa.Enum('user', 'system', 'service', name='temporalexecutionownertype'), server_default='user', nullable=False),
    sa.Column('state', sa.Enum('initializing', 'planning', 'executing', 'awaiting_external', 'finalizing', 'succeeded', 'failed', 'canceled', name='moonmindworkflowstate'), server_default='initializing', nullable=False),
    sa.Column('close_status', sa.Enum('completed', 'failed', 'canceled', 'terminated', 'timed_out', 'continued_as_new', name='temporalexecutionclosestatus'), nullable=True),
    sa.Column('entry', sa.String(length=16), nullable=False),
    sa.Column('search_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('memo', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('artifact_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_ref', sa.String(length=512), nullable=True),
    sa.Column('plan_ref', sa.String(length=512), nullable=True),
    sa.Column('manifest_ref', sa.String(length=512), nullable=True),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('integration_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('pending_parameters_patch', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('awaiting_external', sa.Boolean(), nullable=False),
    sa.Column('waiting_reason', sa.String(length=32), nullable=True),
    sa.Column('attention_required', sa.Boolean(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('wait_cycle_count', sa.Integer(), nullable=False),
    sa.Column('rerun_count', sa.Integer(), nullable=False),
    sa.Column('create_idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('last_update_idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('last_update_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('projection_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_state', sa.Enum('fresh', 'stale', 'repair_pending', 'orphaned', name='temporalexecutionprojectionsyncstate'), server_default='fresh', nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('source_mode', sa.Enum('projection_only', 'mixed', 'temporal_authoritative', name='temporalexecutionprojectionsourcemode'), server_default='projection_only', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('workflow_id'),
    sa.UniqueConstraint('create_idempotency_key', 'owner_id', 'owner_type', 'workflow_type', name='uq_temporal_executions_create_idempotency_owner_type')
    )
    op.create_index('ix_temporal_executions_owner_state', 'temporal_executions', ['owner_id', 'state'], unique=False)
    op.create_index('ix_temporal_executions_state_updated_at', 'temporal_executions', ['state', 'updated_at'], unique=False)
    op.create_index('ix_temporal_executions_type_updated_at', 'temporal_executions', ['workflow_type', 'updated_at'], unique=False)
    op.create_table('user',
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('oidc_provider', sa.String(length=32), nullable=True),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oidc_provider', 'oidc_subject', name='uq_oidc_identity')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_oidc_provider'), 'user', ['oidc_provider'], unique=False)
    op.create_index(op.f('ix_user_oidc_subject'), 'user', ['oidc_subject'], unique=False)
    op.create_table('agent_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', 'dead_letter', name='agentjobstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('cancel_requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('affinity_key', sa.String(length=255), nullable=True),
    sa.Column('claimed_by', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('finish_outcome_code', sa.String(length=64), nullable=True),
    sa.Column('finish_outcome_stage', sa.String(length=32), nullable=True),
    sa.Column('finish_outcome_reason', sa.String(length=256), nullable=True),
    sa.Column('finish_summary_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('artifacts_path', sa.String(length=1024), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cancel_requested_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_jobs_created_at_id', 'agent_jobs', ['created_at', 'id'], unique=False)
    op.create_index('ix_agent_jobs_lease_expires_at', 'agent_jobs', ['lease_expires_at'], unique=False)
    op.create_index('ix_agent_jobs_status_created_at_id', 'agent_jobs', ['status', 'created_at', 'id'], unique=False)
    op.create_index('ix_agent_jobs_status_priority_created_at', 'agent_jobs', ['status', 'priority', 'created_at'], unique=False)
    op.create_index('ix_agent_jobs_type_status_created_at', 'agent_jobs', ['type', 'status', 'created_at'], unique=False)
    op.create_table('automation_agent_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_backend', sa.String(length=128), nullable=False),
    sa.Column('agent_version', sa.String(length=128), nullable=False),
    sa.Column('prompt_pack_version', sa.String(length=128), nullable=True),
    sa.Column('runtime_env', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['automation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_automation_agent_config_run')
    )
    op.create_table('automation_task_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.Enum('prepare_job', 'start_job_container', 'git_clone', 'speckit_specify', 'speckit_plan', 'speckit_tasks', 'speckit_analyze', 'speckit_implement', 'commit_push', 'open_pr', 'cleanup', name='specautomationphase'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'skipped', 'retrying', name='specautomationtaskstatus'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stdout_path', sa.String(length=1024), nullable=True),
    sa.Column('stderr_path', sa.String(length=1024), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['automation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'phase', 'attempt', name='uq_automation_task_state_attempt')
    )
    op.create_index('ix_automation_task_states_run_id', 'automation_task_states', ['run_id'], unique=False)
    op.create_table('codex_worker_shards',
    sa.Column('queue_name', sa.String(length=64), nullable=False),
    sa.Column('volume_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'draining', 'offline', name='codexworkershardstatus'), nullable=False),
    sa.Column('hash_modulo', sa.Integer(), nullable=False),
    sa.Column('worker_hostname', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['volume_name'], ['codex_auth_volumes.name'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('queue_name'),
    sa.UniqueConstraint('volume_name', name='uq_codex_worker_shards_volume_name')
    )
    op.create_table('orchestrator_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('target_service', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Enum('normal', 'high', name='orchestratorrunpriority'), server_default='normal', nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'awaiting_approval', 'succeeded', 'failed', 'rolled_back', name='orchestratorrunstatus'), server_default='pending', nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_token', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True),
    sa.Column('metrics_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('artifact_root', sa.String(length=1024), nullable=True),
    sa.Column('action_plan_id', sa.Uuid(), nullable=False),
    sa.Column('approval_gate_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR (started_at IS NOT NULL AND completed_at >= started_at)', name='ck_orchestrator_runs_timestamps'),
    sa.ForeignKeyConstraint(['action_plan_id'], ['orchestrator_action_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['approval_gate_id'], ['approval_gates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orchestrator_runs_status', 'orchestrator_runs', ['status'], unique=False)
    op.create_index('ix_orchestrator_runs_target_service', 'orchestrator_runs', ['target_service'], unique=False)
    op.create_table('recurring_task_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.Enum('cron', name='recurringtaskscheduletype'), nullable=False),
    sa.Column('cron', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=128), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_dispatch_status', sa.String(length=32), nullable=True),
    sa.Column('last_dispatch_error', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('scope_type', sa.Enum('personal', 'team', 'global', name='recurringtaskscopetype'), nullable=False),
    sa.Column('scope_ref', sa.String(length=255), nullable=True),
    sa.Column('target', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recurring_task_definitions_enabled_next_run_at', 'recurring_task_definitions', ['enabled', 'next_run_at'], unique=False)
    op.create_index('ix_recurring_task_definitions_owner_enabled', 'recurring_task_definitions', ['owner_user_id', 'enabled'], unique=False)
    op.create_table('system_control_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('control', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.Enum('drain', 'quiesce', name='workerpausemode'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_control_events_control_created_at', 'system_control_events', ['control', 'created_at'], unique=False)
    op.create_table('system_worker_pause_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.Enum('drain', 'quiesce', name='workerpausemode'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_step_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('scope_type', sa.Enum('global', 'team', 'personal', name='tasktemplatescopetype'), nullable=False),
    sa.Column('scope_ref', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('required_capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('latest_version_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['latest_version_id'], ['task_step_template_versions.id'], name='fk_task_template_latest_version', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'scope_type', 'scope_ref', name='uq_task_step_template_slug_scope')
    )
    op.create_index('ix_task_step_templates_active', 'task_step_templates', ['is_active'], unique=False)
    op.create_index('ix_task_step_templates_scope', 'task_step_templates', ['scope_type', 'scope_ref'], unique=False)
    op.create_index('ix_task_step_templates_slug', 'task_step_templates', ['slug'], unique=False)
    op.create_table('temporal_artifact_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('link_type', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_activity_type', sa.String(length=255), nullable=True),
    sa.Column('created_by_worker', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['temporal_artifacts.artifact_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temporal_artifact_links_artifact_id', 'temporal_artifact_links', ['artifact_id'], unique=False)
    op.create_index('ix_temporal_artifact_links_execution', 'temporal_artifact_links', ['namespace', 'workflow_id', 'run_id', 'link_type', 'created_at'], unique=False)
    op.create_table('temporal_artifact_pins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('pinned_by_principal', sa.String(length=255), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['temporal_artifacts.artifact_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', name='uq_temporal_artifact_pins_artifact_id')
    )
    op.create_table('temporal_integration_correlations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_name', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('callback_correlation_key', sa.String(length=128), nullable=True),
    sa.Column('external_operation_id', sa.String(length=255), nullable=True),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['temporal_executions.workflow_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_name', 'callback_correlation_key', name='uq_temporal_integration_correlations_callback_key'),
    sa.UniqueConstraint('integration_name', 'external_operation_id', name='uq_temporal_integration_correlations_operation_id')
    )
    op.create_index('ix_temporal_integration_correlations_workflow_status', 'temporal_integration_correlations', ['workflow_id', 'lifecycle_status'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('google_api_key_encrypted', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True),
    sa.Column('openai_api_key_encrypted', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True),
    sa.Column('github_token_encrypted', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=False)
    op.create_table('agent_job_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('digest', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['agent_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_job_artifacts_job_id_created_at', 'agent_job_artifacts', ['job_id', 'created_at'], unique=False)
    op.create_index('ix_agent_job_artifacts_job_id_name', 'agent_job_artifacts', ['job_id', 'name'], unique=False)
    op.create_table('agent_job_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Enum('info', 'warn', 'error', name='agentjobeventlevel'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['agent_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_job_events_job_id_created_at', 'agent_job_events', ['job_id', 'created_at'], unique=False)
    op.create_index('ix_agent_job_events_level_created_at', 'agent_job_events', ['level', 'created_at'], unique=False)
    op.create_table('automation_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('task_state_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.Enum('stdout_log', 'stderr_log', 'diff_summary', 'commit_status', 'metrics_snapshot', 'environment_info', name='specautomationartifacttype'), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_phase', sa.Enum('prepare_job', 'start_job_container', 'git_clone', 'speckit_specify', 'speckit_plan', 'speckit_tasks', 'speckit_analyze', 'speckit_implement', 'commit_push', 'open_pr', 'cleanup', name='specautomationphase'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['automation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_state_id'], ['automation_task_states.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'artifact_type', 'storage_path', name='uq_automation_artifact_path')
    )
    op.create_index('ix_automation_artifacts_run_id', 'automation_artifacts', ['run_id'], unique=False)
    op.create_table('orchestrator_run_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.Enum('patch_diff', 'build_log', 'verify_log', 'rollback_log', 'metrics', 'plan_snapshot', name='orchestratorrunartifacttype'), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes IS NULL OR size_bytes >= 0', name='ck_orchestrator_artifacts_size_non_negative'),
    sa.ForeignKeyConstraint(['run_id'], ['orchestrator_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'artifact_type', 'path', name='uq_orchestrator_artifact_path')
    )
    op.create_index('ix_orchestrator_run_artifacts_run_id', 'orchestrator_run_artifacts', ['run_id'], unique=False)
    op.create_table('orchestrator_task_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.String(length=128), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.String(length=128), nullable=False),
    sa.Column('skill_args', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'skipped', name='orchestratortaskstepstatus'), server_default='queued', nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('artifact_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt >= 1', name='ck_orchestrator_task_step_attempt_positive'),
    sa.CheckConstraint('step_index >= 0', name='ck_orchestrator_task_step_index'),
    sa.ForeignKeyConstraint(['task_id'], ['orchestrator_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'step_id', name='uq_orchestrator_task_step_id')
    )
    op.create_index('ix_orchestrator_task_steps_task_id', 'orchestrator_task_steps', ['task_id', 'step_index'], unique=False)
    op.create_table('recurring_task_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger', sa.Enum('schedule', 'manual', name='recurringtaskruntrigger'), nullable=False),
    sa.Column('outcome', sa.Enum('pending_dispatch', 'enqueued', 'skipped', 'dispatch_error', name='recurringtaskrunoutcome'), nullable=False),
    sa.Column('dispatch_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dispatch_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queue_job_id', sa.Uuid(), nullable=True),
    sa.Column('queue_job_type', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['recurring_task_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_id', 'scheduled_for', name='uq_recurring_task_runs_definition_scheduled_for')
    )
    op.create_index('ix_recurring_task_runs_definition_created_at', 'recurring_task_runs', ['definition_id', 'created_at'], unique=False)
    op.create_index('ix_recurring_task_runs_outcome_dispatch_after', 'recurring_task_runs', ['outcome', 'dispatch_after'], unique=False)
    op.create_table('task_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('open', 'promoted', 'dismissed', 'accepted', 'rejected', name='taskproposalstatus'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('dedup_key', sa.String(length=512), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('review_priority', sa.Enum('low', 'normal', 'high', 'urgent', name='taskproposalpriority'), nullable=False),
    sa.Column('priority_override_reason', sa.Text(), nullable=True),
    sa.Column('task_create_request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('proposed_by_worker_id', sa.String(length=255), nullable=True),
    sa.Column('proposed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('origin_source', sa.Enum('queue', 'orchestrator', 'workflow', 'manual', name='taskproposaloriginsource'), nullable=False),
    sa.Column('origin_id', sa.Uuid(), nullable=True),
    sa.Column('origin_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('promoted_job_id', sa.Uuid(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promoted_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promoted_job_id'], ['agent_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promoted_job_id', name='uq_task_proposals_promoted_job_id')
    )
    op.create_index('ix_task_proposals_dedup_hash_status', 'task_proposals', ['dedup_hash', 'status'], unique=False)
    op.create_index('ix_task_proposals_origin', 'task_proposals', ['origin_source', 'origin_id'], unique=False)
    op.create_index('ix_task_proposals_priority_created', 'task_proposals', ['review_priority', 'created_at'], unique=False)
    op.create_index('ix_task_proposals_repository', 'task_proposals', ['repository'], unique=False)
    op.create_index('ix_task_proposals_status_created', 'task_proposals', ['status', 'created_at'], unique=False)
    op.create_table('task_run_control_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_run_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_run_id'], ['agent_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_run_control_events_action_created_at', 'task_run_control_events', ['action', 'created_at'], unique=False)
    op.create_index('ix_task_run_control_events_task_run_id_created_at', 'task_run_control_events', ['task_run_id', 'created_at'], unique=False)
    op.create_table('task_run_live_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_run_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('tmate', name='agentjoblivesessionprovider'), nullable=False),
    sa.Column('status', sa.Enum('disabled', 'starting', 'ready', 'revoked', 'ended', 'error', name='agentjoblivesessionstatus'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('worker_hostname', sa.String(length=255), nullable=True),
    sa.Column('tmate_session_name', sa.String(length=255), nullable=True),
    sa.Column('tmate_socket_path', sa.String(length=1024), nullable=True),
    sa.Column('attach_ro', sa.Text(), nullable=True),
    sa.Column('attach_rw_encrypted', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True),
    sa.Column('web_ro', sa.Text(), nullable=True),
    sa.Column('web_rw_encrypted', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True),
    sa.Column('rw_granted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_run_id'], ['agent_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_run_id')
    )
    op.create_index('ix_task_run_live_sessions_last_heartbeat_at', 'task_run_live_sessions', ['last_heartbeat_at'], unique=False)
    op.create_index('ix_task_run_live_sessions_status_expires_at', 'task_run_live_sessions', ['status', 'expires_at'], unique=False)
    op.create_index('ix_task_run_live_sessions_worker_id', 'task_run_live_sessions', ['worker_id'], unique=False)
    op.create_table('task_step_template_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['task_step_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'template_id', name='uq_task_template_favorite')
    )
    op.create_index('ix_task_step_template_favorites_user', 'task_step_template_favorites', ['user_id'], unique=False)
    op.create_table('task_step_template_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('inputs_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('annotations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('required_capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('max_step_count', sa.Integer(), nullable=False),
    sa.Column('release_status', sa.Enum('draft', 'active', 'inactive', name='tasktemplatereleasestatus'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('seed_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['task_step_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uq_task_step_template_version_label')
    )
    op.create_index('ix_task_step_template_versions_template', 'task_step_template_versions', ['template_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feature_key', sa.String(length=255), nullable=False),
    sa.Column('legacy_chain_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'no_work', 'cancelled', 'retrying', name='specworkflowrunstatus'), nullable=False),
    sa.Column('phase', sa.Enum('discover', 'submit', 'apply', 'publish', 'complete', name='specworkflowrunphase'), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('repository', sa.String(length=255), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('codex_task_id', sa.String(length=255), nullable=True),
    sa.Column('codex_queue', sa.String(length=64), nullable=True),
    sa.Column('codex_volume', sa.String(length=64), nullable=True),
    sa.Column('codex_preflight_status', sa.Enum('pending', 'passed', 'failed', 'skipped', name='codexpreflightstatus'), nullable=True),
    sa.Column('codex_preflight_message', sa.Text(), nullable=True),
    sa.Column('codex_logs_path', sa.String(length=1024), nullable=True),
    sa.Column('codex_patch_path', sa.String(length=1024), nullable=True),
    sa.Column('artifacts_path', sa.String(length=512), nullable=True),
    sa.Column('current_task_name', sa.Enum('discover', 'submit', 'apply', 'publish', 'finalize', 'retry-hook', name='specworkflowtaskname'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['codex_queue'], ['codex_worker_shards.queue_name'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['codex_volume'], ['codex_auth_volumes.name'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_runs_created_by', 'workflow_runs', ['created_by'], unique=False)
    op.create_index('ix_workflow_runs_feature_key', 'workflow_runs', ['feature_key'], unique=False)
    op.create_index('ix_workflow_runs_requested_by', 'workflow_runs', ['requested_by_user_id'], unique=False)
    op.create_index('ix_workflow_runs_status', 'workflow_runs', ['status'], unique=False)
    op.create_table('task_proposal_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['task_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'target', name='uq_task_proposal_notifications_proposal_target')
    )
    op.create_table('task_step_template_recents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_version_id'], ['task_step_template_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'template_version_id', name='uq_task_template_recent_user_version')
    )
    op.create_index('ix_task_step_template_recents_user', 'task_step_template_recents', ['user_id'], unique=False)
    op.create_table('workflow_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_run_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.Enum('codex_logs', 'codex_patch', 'gh_push_log', 'gh_pr_response', 'apply_output', 'pr_payload', 'retry_context', name='workflowartifacttype'), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('digest', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_run_id', 'artifact_type', 'path', name='uq_workflow_artifact_path')
    )
    op.create_index('ix_workflow_artifacts_run_id', 'workflow_artifacts', ['workflow_run_id'], unique=False)
    op.create_table('workflow_credential_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_run_id', sa.Uuid(), nullable=False),
    sa.Column('codex_status', sa.Enum('valid', 'invalid', 'expires_soon', name='workflowcodexcredentialstatus'), nullable=False),
    sa.Column('github_status', sa.Enum('valid', 'invalid', 'scope_missing', name='workflowgithubcredentialstatus'), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('codex_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('codex_message', sa.Text(), nullable=True),
    sa.Column('github_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_message', sa.Text(), nullable=True),
    sa.Column('environment_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_run_id', name='uq_workflow_credential_audit_run')
    )
    op.create_index('ix_workflow_credential_audits_run', 'workflow_credential_audits', ['workflow_run_id'], unique=False)
    op.create_table('workflow_task_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_run_id', sa.Uuid(), nullable=True),
    sa.Column('orchestrator_run_id', sa.Uuid(), nullable=True),
    sa.Column('task_name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'skipped', name='specworkflowtaskstatus'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('plan_step', sa.Enum('analyze', 'patch', 'build', 'restart', 'verify', 'rollback', name='orchestratorplanstep'), nullable=True),
    sa.Column('plan_step_status', sa.Enum('pending', 'in_progress', 'succeeded', 'failed', 'skipped', name='orchestratorplanstepstatus'), nullable=True),
    sa.Column('worker_state', sa.Enum('PENDING', 'STARTED', 'RETRY', 'SUCCESS', 'FAILURE', name='orchestratortaskstate'), nullable=True),
    sa.Column('worker_task_id', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('artifact_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(orchestrator_run_id IS NULL) OR (plan_step IS NOT NULL)', name='ck_workflow_task_state_orchestrator_plan_step'),
    sa.CheckConstraint('(workflow_run_id IS NOT NULL AND orchestrator_run_id IS NULL) OR (workflow_run_id IS NULL AND orchestrator_run_id IS NOT NULL)', name='ck_workflow_task_state_run_id_exclusive'),
    sa.CheckConstraint('(workflow_run_id IS NULL) OR (task_name IS NOT NULL)', name='ck_workflow_task_state_task_name_required'),
    sa.ForeignKeyConstraint(['orchestrator_run_id'], ['orchestrator_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orchestrator_run_id', 'plan_step', 'attempt', name='uq_orchestrator_task_state_attempt'),
    sa.UniqueConstraint('workflow_run_id', 'task_name', 'attempt', name='uq_workflow_task_state_attempt')
    )
    op.create_index('ix_workflow_task_states_failed', 'workflow_task_states', ['workflow_run_id'], unique=False, postgresql_where=sa.text("status = 'failed'"))
    op.create_index('ix_workflow_task_states_orchestrator_run_id', 'workflow_task_states', ['orchestrator_run_id'], unique=False)
    op.create_index('ix_workflow_task_states_run_id', 'workflow_task_states', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_task_states_run_id', table_name='workflow_task_states')
    op.drop_index('ix_workflow_task_states_orchestrator_run_id', table_name='workflow_task_states')
    op.drop_index('ix_workflow_task_states_failed', table_name='workflow_task_states', postgresql_where=sa.text("status = 'failed'"))
    op.drop_table('workflow_task_states')
    op.drop_index('ix_workflow_credential_audits_run', table_name='workflow_credential_audits')
    op.drop_table('workflow_credential_audits')
    op.drop_index('ix_workflow_artifacts_run_id', table_name='workflow_artifacts')
    op.drop_table('workflow_artifacts')
    op.drop_index('ix_task_step_template_recents_user', table_name='task_step_template_recents')
    op.drop_table('task_step_template_recents')
    op.drop_table('task_proposal_notifications')
    op.drop_index('ix_workflow_runs_status', table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_requested_by', table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_feature_key', table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_created_by', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index('ix_task_step_template_versions_template', table_name='task_step_template_versions')
    op.drop_table('task_step_template_versions')
    op.drop_index('ix_task_step_template_favorites_user', table_name='task_step_template_favorites')
    op.drop_table('task_step_template_favorites')
    op.drop_index('ix_task_run_live_sessions_worker_id', table_name='task_run_live_sessions')
    op.drop_index('ix_task_run_live_sessions_status_expires_at', table_name='task_run_live_sessions')
    op.drop_index('ix_task_run_live_sessions_last_heartbeat_at', table_name='task_run_live_sessions')
    op.drop_table('task_run_live_sessions')
    op.drop_index('ix_task_run_control_events_task_run_id_created_at', table_name='task_run_control_events')
    op.drop_index('ix_task_run_control_events_action_created_at', table_name='task_run_control_events')
    op.drop_table('task_run_control_events')
    op.drop_index('ix_task_proposals_status_created', table_name='task_proposals')
    op.drop_index('ix_task_proposals_repository', table_name='task_proposals')
    op.drop_index('ix_task_proposals_priority_created', table_name='task_proposals')
    op.drop_index('ix_task_proposals_origin', table_name='task_proposals')
    op.drop_index('ix_task_proposals_dedup_hash_status', table_name='task_proposals')
    op.drop_table('task_proposals')
    op.drop_index('ix_recurring_task_runs_outcome_dispatch_after', table_name='recurring_task_runs')
    op.drop_index('ix_recurring_task_runs_definition_created_at', table_name='recurring_task_runs')
    op.drop_table('recurring_task_runs')
    op.drop_index('ix_orchestrator_task_steps_task_id', table_name='orchestrator_task_steps')
    op.drop_table('orchestrator_task_steps')
    op.drop_index('ix_orchestrator_run_artifacts_run_id', table_name='orchestrator_run_artifacts')
    op.drop_table('orchestrator_run_artifacts')
    op.drop_index('ix_automation_artifacts_run_id', table_name='automation_artifacts')
    op.drop_table('automation_artifacts')
    op.drop_index('ix_agent_job_events_level_created_at', table_name='agent_job_events')
    op.drop_index('ix_agent_job_events_job_id_created_at', table_name='agent_job_events')
    op.drop_table('agent_job_events')
    op.drop_index('ix_agent_job_artifacts_job_id_name', table_name='agent_job_artifacts')
    op.drop_index('ix_agent_job_artifacts_job_id_created_at', table_name='agent_job_artifacts')
    op.drop_table('agent_job_artifacts')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index('ix_temporal_integration_correlations_workflow_status', table_name='temporal_integration_correlations')
    op.drop_table('temporal_integration_correlations')
    op.drop_table('temporal_artifact_pins')
    op.drop_index('ix_temporal_artifact_links_execution', table_name='temporal_artifact_links')
    op.drop_index('ix_temporal_artifact_links_artifact_id', table_name='temporal_artifact_links')
    op.drop_table('temporal_artifact_links')
    op.drop_index('ix_task_step_templates_slug', table_name='task_step_templates')
    op.drop_index('ix_task_step_templates_scope', table_name='task_step_templates')
    op.drop_index('ix_task_step_templates_active', table_name='task_step_templates')
    op.drop_table('task_step_templates')
    op.drop_table('system_worker_pause_state')
    op.drop_index('ix_system_control_events_control_created_at', table_name='system_control_events')
    op.drop_table('system_control_events')
    op.drop_index('ix_recurring_task_definitions_owner_enabled', table_name='recurring_task_definitions')
    op.drop_index('ix_recurring_task_definitions_enabled_next_run_at', table_name='recurring_task_definitions')
    op.drop_table('recurring_task_definitions')
    op.drop_index('ix_orchestrator_runs_target_service', table_name='orchestrator_runs')
    op.drop_index('ix_orchestrator_runs_status', table_name='orchestrator_runs')
    op.drop_table('orchestrator_runs')
    op.drop_table('codex_worker_shards')
    op.drop_index('ix_automation_task_states_run_id', table_name='automation_task_states')
    op.drop_table('automation_task_states')
    op.drop_table('automation_agent_configs')
    op.drop_index('ix_agent_jobs_type_status_created_at', table_name='agent_jobs')
    op.drop_index('ix_agent_jobs_status_priority_created_at', table_name='agent_jobs')
    op.drop_index('ix_agent_jobs_status_created_at_id', table_name='agent_jobs')
    op.drop_index('ix_agent_jobs_lease_expires_at', table_name='agent_jobs')
    op.drop_index('ix_agent_jobs_created_at_id', table_name='agent_jobs')
    op.drop_table('agent_jobs')
    op.drop_index(op.f('ix_user_oidc_subject'), table_name='user')
    op.drop_index(op.f('ix_user_oidc_provider'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index('ix_temporal_executions_type_updated_at', table_name='temporal_executions')
    op.drop_index('ix_temporal_executions_state_updated_at', table_name='temporal_executions')
    op.drop_index('ix_temporal_executions_owner_state', table_name='temporal_executions')
    op.drop_table('temporal_executions')
    op.drop_index('ix_temporal_execution_sources_type_updated_at', table_name='temporal_execution_sources')
    op.drop_index('ix_temporal_execution_sources_state_updated_at', table_name='temporal_execution_sources')
    op.drop_index('ix_temporal_execution_sources_owner_state', table_name='temporal_execution_sources')
    op.drop_table('temporal_execution_sources')
    op.drop_index('ix_temporal_artifacts_status', table_name='temporal_artifacts')
    op.drop_index('ix_temporal_artifacts_hard_deleted_at', table_name='temporal_artifacts')
    op.drop_index('ix_temporal_artifacts_expires_at', table_name='temporal_artifacts')
    op.drop_index('ix_temporal_artifacts_deleted_at', table_name='temporal_artifacts')
    op.drop_index('ix_temporal_artifacts_created_at', table_name='temporal_artifacts')
    op.drop_table('temporal_artifacts')
    op.drop_index('ix_task_source_mappings_source_record_id', table_name='task_source_mappings')
    op.drop_index('ix_task_source_mappings_source_entry', table_name='task_source_mappings')
    op.drop_table('task_source_mappings')
    op.drop_table('orchestrator_action_plans')
    op.drop_index(op.f('ix_manifest_id'), table_name='manifest')
    op.drop_table('manifest')
    op.drop_index('ix_auth_profiles_runtime', table_name='managed_agent_auth_profiles')
    op.drop_index('ix_auth_profiles_enabled', table_name='managed_agent_auth_profiles')
    op.drop_table('managed_agent_auth_profiles')
    op.drop_table('codex_auth_volumes')
    op.drop_index('ix_automation_runs_status', table_name='automation_runs')
    op.drop_index('ix_automation_runs_repository', table_name='automation_runs')
    op.drop_index('ix_automation_runs_external_ref', table_name='automation_runs')
    op.drop_index('ix_automation_runs_created_at', table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_table('approval_gates')
    op.drop_index('ix_agent_worker_tokens_worker_id', table_name='agent_worker_tokens')
    op.drop_index('ix_agent_worker_tokens_is_active', table_name='agent_worker_tokens')
    op.drop_index('ix_agent_worker_tokens_created_at', table_name='agent_worker_tokens')
    op.drop_table('agent_worker_tokens')
    # ### end Alembic commands ###
