"""remove task run id fk

Revision ID: 59830c78b458
Revises: b3e7a91c2d4f
Create Date: 2026-03-19 23:33:35.335021

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '59830c78b458'
down_revision: Union[str, None] = 'b3e7a91c2d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_run_live_sessions_task_run_id_key', 'task_run_live_sessions', type_='unique')
    op.create_index(op.f('ix_task_run_live_sessions_task_run_id'), 'task_run_live_sessions', ['task_run_id'], unique=True)
    op.drop_constraint('task_run_live_sessions_task_run_id_fkey', 'task_run_live_sessions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('task_run_live_sessions_task_run_id_fkey', 'task_run_live_sessions', 'agent_jobs', ['task_run_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_task_run_live_sessions_task_run_id'), table_name='task_run_live_sessions')
    op.create_unique_constraint('task_run_live_sessions_task_run_id_key', 'task_run_live_sessions', ['task_run_id'])
    # ### end Alembic commands ###
