"""add_default_model_and_model_overrides_to_provider_profiles

Revision ID: 7743cec3c465
Revises: 1a2b3c4d5e6f
Create Date: 2026-03-28 14:49:17.576801

"""
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7743cec3c465'
down_revision: Union[str, None] = '1a2b3c4d5e6f'

# Export required Alembic globals to suppress unused-variable warnings
__all__ = ['revision', 'down_revision', 'upgrade', 'downgrade']

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_agent_provider_profiles', sa.Column('default_model', sa.String(length=255), nullable=True))
    op.add_column('managed_agent_provider_profiles', sa.Column('model_overrides', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    raise NotImplementedError("One-way migration: Provider Profiles Phase 2")
