"""Phase_5_OAuthSession

Revision ID: 7bd7130eae51
Revises: 7743cec3c465
Create Date: 2026-03-28 15:50:09.085346

"""
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd7130eae51'
down_revision: Union[str, None] = '7743cec3c465'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_agent_oauth_sessions', sa.Column('terminal_session_id', sa.String(length=128), nullable=True))
    op.add_column('managed_agent_oauth_sessions', sa.Column('terminal_bridge_id', sa.String(length=128), nullable=True))
    op.add_column('managed_agent_oauth_sessions', sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('managed_agent_oauth_sessions', sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('managed_agent_oauth_sessions', 'oauth_ssh_url')
    op.drop_column('managed_agent_oauth_sessions', 'oauth_web_url')
    # PostgreSQL requires ALTER TYPE ADD VALUE to be committed before the new value
    # can be used in DML statements. Commit the current transaction, then add the
    # enum value (it auto-commits in the resulting autocommit context), and proceed.
    connection = op.get_bind()
    connection.execute(sa.text("COMMIT"))
    connection.execute(sa.text("ALTER TYPE oauthsessionstatus ADD VALUE IF NOT EXISTS 'bridge_ready'"))
    connection.execute(sa.text(
        "UPDATE managed_agent_oauth_sessions SET status = 'bridge_ready' "
        "WHERE status = 'oauth_runner_ready'"
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_agent_oauth_sessions', sa.Column('oauth_web_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('managed_agent_oauth_sessions', sa.Column('oauth_ssh_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('managed_agent_oauth_sessions', 'disconnected_at')
    op.drop_column('managed_agent_oauth_sessions', 'connected_at')
    op.drop_column('managed_agent_oauth_sessions', 'terminal_bridge_id')
    op.drop_column('managed_agent_oauth_sessions', 'terminal_session_id')
    # ### end Alembic commands ###
