"""add_oidc_columns_to_user_table

Revision ID: 9e9bd65e1b9e
Revises: 33e4b7073b5d
Create Date: 2025-06-30 20:12:16.032215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9bd65e1b9e'
down_revision: Union[str, None] = '33e4b7073b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oidc_provider', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('oidc_subject', sa.String(length=255), nullable=True))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               nullable=True)
    op.create_index(op.f('ix_user_oidc_provider'), 'user', ['oidc_provider'], unique=False)
    op.create_index(op.f('ix_user_oidc_subject'), 'user', ['oidc_subject'], unique=False)
    op.create_unique_constraint('uq_oidc_identity', 'user', ['oidc_provider', 'oidc_subject'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_oidc_identity', 'user', type_='unique')
    op.drop_index(op.f('ix_user_oidc_subject'), table_name='user')
    op.drop_index(op.f('ix_user_oidc_provider'), table_name='user')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('user', 'oidc_subject')
    op.drop_column('user', 'oidc_provider')
    # ### end Alembic commands ###
