"""agent_skill_system_phase_2

Revision ID: b47e8ad48d4c
Revises: 7bd7130eae51
Create Date: 2026-03-30 13:08:46.956250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b47e8ad48d4c'
down_revision: Union[str, None] = '7bd7130eae51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_skill_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_skill_definitions_slug', 'agent_skill_definitions', ['slug'], unique=True)
    op.create_table('skill_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skill_sets_slug', 'skill_sets', ['slug'], unique=True)
    op.create_table('agent_skill_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('version_string', sa.String(length=64), nullable=False),
    sa.Column('format', sa.Enum('markdown', 'bundle', name='agentskillformat'), nullable=False),
    sa.Column('artifact_ref', sa.String(length=1024), nullable=False),
    sa.Column('content_digest', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['agent_skill_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'version_string', name='uq_agent_skill_version_string')
    )
    op.create_index('ix_agent_skill_versions_skill', 'agent_skill_versions', ['skill_id'], unique=False)
    op.create_table('skill_set_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skill_set_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('version_constraint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['agent_skill_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_set_id'], ['skill_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_set_id', 'skill_id', name='uq_skill_set_entry')
    )
    op.create_index('ix_skill_set_entries_set', 'skill_set_entries', ['skill_set_id'], unique=False)
    op.add_column('user_profile', sa.Column('agent_skill_repo_sources_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('user_profile', sa.Column('agent_skill_local_sources_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'agent_skill_local_sources_enabled')
    op.drop_column('user_profile', 'agent_skill_repo_sources_enabled')
    op.drop_index('ix_skill_set_entries_set', table_name='skill_set_entries')
    op.drop_table('skill_set_entries')
    op.drop_index('ix_agent_skill_versions_skill', table_name='agent_skill_versions')
    op.drop_table('agent_skill_versions')
    op.drop_index('ix_skill_sets_slug', table_name='skill_sets')
    op.drop_table('skill_sets')
    op.drop_index('ix_agent_skill_definitions_slug', table_name='agent_skill_definitions')
    op.drop_table('agent_skill_definitions')
    # ### end Alembic commands ###
