"""Remove legacy queue backend tables

Revision ID: b92f4891f27c
Revises: 3b27177de0fe
Create Date: 2026-03-22 01:49:56.660335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b92f4891f27c'
down_revision: Union[str, None] = '3b27177de0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_run_live_sessions_last_heartbeat_at'), table_name='task_run_live_sessions')
    op.drop_index(op.f('ix_task_run_live_sessions_status_expires_at'), table_name='task_run_live_sessions')
    op.drop_index(op.f('ix_task_run_live_sessions_task_run_id'), table_name='task_run_live_sessions')
    op.drop_index(op.f('ix_task_run_live_sessions_worker_id'), table_name='task_run_live_sessions')
    op.drop_table('task_run_live_sessions')
    op.drop_index(op.f('ix_system_control_events_control_created_at'), table_name='system_control_events')
    op.drop_table('system_control_events')
    op.drop_table('system_worker_pause_state')
    op.drop_index(op.f('ix_agent_worker_tokens_created_at'), table_name='agent_worker_tokens')
    op.drop_index(op.f('ix_agent_worker_tokens_is_active'), table_name='agent_worker_tokens')
    op.drop_index(op.f('ix_agent_worker_tokens_worker_id'), table_name='agent_worker_tokens')
    op.drop_table('agent_worker_tokens')
    op.drop_index(op.f('ix_agent_jobs_created_at_id'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_lease_expires_at'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_status_created_at_id'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_status_priority_created_at'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_type_status_created_at'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_job_artifacts_job_id_created_at'), table_name='agent_job_artifacts')
    op.drop_index(op.f('ix_agent_job_artifacts_job_id_name'), table_name='agent_job_artifacts')
    op.drop_table('agent_job_artifacts')
    op.drop_index(op.f('ix_task_run_control_events_action_created_at'), table_name='task_run_control_events')
    op.drop_index(op.f('ix_task_run_control_events_task_run_id_created_at'), table_name='task_run_control_events')
    op.drop_table('task_run_control_events')
    op.drop_index(op.f('ix_agent_job_events_job_id_created_at'), table_name='agent_job_events')
    op.drop_index(op.f('ix_agent_job_events_level_created_at'), table_name='agent_job_events')
    op.drop_table('agent_job_events')
    op.add_column('recurring_task_runs', sa.Column('temporal_workflow_id', sa.String(length=128), nullable=True))
    op.add_column('recurring_task_runs', sa.Column('temporal_run_id', sa.String(length=64), nullable=True))
    op.drop_column('recurring_task_runs', 'queue_job_id')
    op.drop_column('recurring_task_runs', 'queue_job_type')
    op.drop_constraint(op.f('uq_task_proposals_promoted_job_id'), 'task_proposals', type_='unique')
    op.drop_constraint(op.f('task_proposals_promoted_job_id_fkey'), 'task_proposals', type_='foreignkey')
    op.drop_column('task_proposals', 'promoted_job_id')
    op.create_foreign_key('fk_task_template_latest_version', 'task_step_templates', 'task_step_template_versions', ['latest_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.drop_column('temporal_execution_sources', 'scheduled_for')
    op.drop_table('agent_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temporal_execution_sources', sa.Column('scheduled_for', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint('fk_task_template_latest_version', 'task_step_templates', type_='foreignkey')
    op.add_column('task_proposals', sa.Column('promoted_job_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('task_proposals_promoted_job_id_fkey'), 'task_proposals', 'agent_jobs', ['promoted_job_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('uq_task_proposals_promoted_job_id'), 'task_proposals', ['promoted_job_id'], postgresql_nulls_not_distinct=False)
    op.add_column('recurring_task_runs', sa.Column('queue_job_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('recurring_task_runs', sa.Column('queue_job_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('recurring_task_runs', 'temporal_run_id')
    op.drop_column('recurring_task_runs', 'temporal_workflow_id')
    op.create_table('agent_job_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('level', postgresql.ENUM('info', 'warn', 'error', name='agentjobeventlevel'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['agent_jobs.id'], name=op.f('agent_job_events_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_job_events_pkey'))
    )
    op.create_index(op.f('ix_agent_job_events_level_created_at'), 'agent_job_events', ['level', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_job_events_job_id_created_at'), 'agent_job_events', ['job_id', 'created_at'], unique=False)
    op.create_table('task_run_control_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], name=op.f('task_run_control_events_actor_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_run_id'], ['agent_jobs.id'], name=op.f('task_run_control_events_task_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_run_control_events_pkey'))
    )
    op.create_index(op.f('ix_task_run_control_events_task_run_id_created_at'), 'task_run_control_events', ['task_run_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_task_run_control_events_action_created_at'), 'task_run_control_events', ['action', 'created_at'], unique=False)
    op.create_table('agent_job_artifacts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('digest', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('storage_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['agent_jobs.id'], name=op.f('agent_job_artifacts_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_job_artifacts_pkey'))
    )
    op.create_index(op.f('ix_agent_job_artifacts_job_id_name'), 'agent_job_artifacts', ['job_id', 'name'], unique=False)
    op.create_index(op.f('ix_agent_job_artifacts_job_id_created_at'), 'agent_job_artifacts', ['job_id', 'created_at'], unique=False)
    op.create_table('agent_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('queued', 'running', 'succeeded', 'failed', 'cancelled', 'dead_letter', name='agentjobstatus'), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('requested_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cancel_requested_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cancel_requested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cancel_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('affinity_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('claimed_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lease_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_attempt_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('attempt', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('finish_outcome_code', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('finish_outcome_stage', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('finish_outcome_reason', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('finish_summary_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('artifacts_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cancel_requested_by_user_id'], ['user.id'], name=op.f('agent_jobs_cancel_requested_by_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('agent_jobs_created_by_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], name=op.f('agent_jobs_requested_by_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_jobs_pkey'))
    )
    op.create_index(op.f('ix_agent_jobs_type_status_created_at'), 'agent_jobs', ['type', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_jobs_status_priority_created_at'), 'agent_jobs', ['status', 'priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_jobs_status_created_at_id'), 'agent_jobs', ['status', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_agent_jobs_lease_expires_at'), 'agent_jobs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_agent_jobs_created_at_id'), 'agent_jobs', ['created_at', 'id'], unique=False)
    op.create_table('agent_worker_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('allowed_repositories', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('allowed_job_types', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('runtime_capabilities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_worker_tokens_pkey')),
    sa.UniqueConstraint('token_hash', name=op.f('agent_worker_tokens_token_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_agent_worker_tokens_worker_id'), 'agent_worker_tokens', ['worker_id'], unique=False)
    op.create_index(op.f('ix_agent_worker_tokens_is_active'), 'agent_worker_tokens', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_worker_tokens_created_at'), 'agent_worker_tokens', ['created_at'], unique=False)
    op.create_table('system_worker_pause_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paused', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mode', postgresql.ENUM('drain', 'quiesce', name='workerpausemode'), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requested_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], name=op.f('system_worker_pause_state_requested_by_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('system_worker_pause_state_pkey'))
    )
    op.create_table('system_control_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('control', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('mode', postgresql.ENUM('drain', 'quiesce', name='workerpausemode'), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actor_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], name=op.f('system_control_events_actor_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('system_control_events_pkey'))
    )
    op.create_index(op.f('ix_system_control_events_control_created_at'), 'system_control_events', ['control', 'created_at'], unique=False)
    op.create_table('task_run_live_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', postgresql.ENUM('none', name='agentjoblivesessionprovider'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('disabled', 'starting', 'ready', 'revoked', 'ended', 'error', name='agentjoblivesessionstatus'), autoincrement=False, nullable=False),
    sa.Column('ready_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('worker_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('worker_hostname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('live_session_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('live_session_socket_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('attach_ro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attach_rw_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('web_ro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('web_rw_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('rw_granted_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_heartbeat_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('task_run_live_sessions_pkey'))
    )
    op.create_index(op.f('ix_task_run_live_sessions_worker_id'), 'task_run_live_sessions', ['worker_id'], unique=False)
    op.create_index(op.f('ix_task_run_live_sessions_task_run_id'), 'task_run_live_sessions', ['task_run_id'], unique=True)
    op.create_index(op.f('ix_task_run_live_sessions_status_expires_at'), 'task_run_live_sessions', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_task_run_live_sessions_last_heartbeat_at'), 'task_run_live_sessions', ['last_heartbeat_at'], unique=False)
    # ### end Alembic commands ###
